### ISSUE TITLE
Suggestion for interface's improvement

### ISSUE THREAD

**Issue by lulivi** [hannesmannerheim/qvitter#114]
Maybe the queet menu (I don't know how to call it)
![d](https://cloud.githubusercontent.com/assets/10894592/6254196/1af4ec46-b7a7-11e4-961e-b1c5d21eccb8.png)
 could be in fixed position, not having to go up when you want to queet.

**Comment by hannesmannerheim** [comment]
thanks for the suggestion. although i don't think it's something i will make. it would make the space for the menu below it, and the history-menu, much smaller. 

you don't have to scroll to the top to write a new queet, there's a button on the header also.

**Comment by lulivi** [comment]
Oh, shit, that's true. Sorry for making you wast time.
