### ISSUE TITLE
Welcome greeting - does not work properly with qvitter?

### ISSUE THREAD

**Issue by knuthollund** [hannesmannerheim/qvitter#116]
There is a setting which can be used in config.php to greet new users.
The setting are beeing picked up by User.php to send a Notice to the newly created users, which greets the user welcome from the user provided in the configuration.
e.g: $config['newuser']['welcome'] = 'youradminusertogreetfrom';

When using this setting, the notification in qvitter does not dissapear and if clicked on "notifications" the message is not displayed (only by clicking mentions).

(Works ok with the standard gnusocial interface).

**Comment by knuthollund** [comment]
![pelle](https://cloud.githubusercontent.com/assets/3600521/6313676/403e83c2-b9b9-11e4-81d4-76ee669ac0a0.png)

**Comment by knuthollund** [comment]
Created a pull request #117 to resolve this issue.

**Comment by knuthollund** [comment]
Here is a screenshot which explains the issue with $notification->whereAdd(sprintf('qvitternotification.created > "%s"', $notification->escape($this->target->created)));

As you see from the screenshot the profile created date is exact the qvitternotification created date, thus it will never be "greater than" > as stated in the query.
![issue_116](https://cloud.githubusercontent.com/assets/3600521/6316435/88674770-ba26-11e4-9804-50baf0f34ecc.jpg)

**Comment by hannesmannerheim** [comment]
this was solved in your pull request, right? closing this, but tell me if it wasn't solved and should be reopened!

**Comment by knuthollund** [comment]
Yes - it was in the pull/merge request. all ok.
