### ISSUE TITLE
Welcome page has no default language

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#124]
Since the split of lang.js the user's page (ex : https://statusnet.lebegue.org/identlud ) comes with not default language. It is rendered with the gnuSocial logo and the language picker only.

**Comment by llebegue** [comment]
It seems closed with the latest commits

**Comment by hannesmannerheim** [comment]
maybe it was because of an error that i introduced in the french translation and fixed here: https://github.com/hannesmannerheim/qvitter/commit/5698e7f2e823f36f4153d846d88b50b02f4bf0cc
