### ISSUE TITLE
Can't display following and followers

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#131]
With this trace :

2015-03-07 17:54:21 LOG_DEBUG: [statusnet.lebegue.org:25452.b74c1204 GET /api/statuses/friends.json?count=20&screen_name=identlud&t=1425750860346] No URL available for notice: id=483087
2015-03-07 17:54:21 LOG_ERR: [statusnet.lebegue.org:25452.b74c1204 GET /api/statuses/friends.json?count=20&screen_name=identlud&t=1425750860346] ServerErrorAction: 400 Invalid URL.
#0 /home/www/gnusocial/local/plugins/Qvitter/QvitterPlugin.php(546): Notice->getUrl()
#1 [internal function]: QvitterPlugin->onNoticeSimpleStatusArray(Object(Notice), Array, Object(Profile), Array)
#2 /home/www/gnusocial/lib/event.php(105): call_user_func_array(Array, Array)
#3 /home/www/gnusocial/lib/apiaction.php(417): Event::handle('NoticeSimpleSta...', Array)
#4 /home/www/gnusocial/lib/apiaction.php(304): ApiAction->twitterSimpleStatusArray(Object(Notice), false)
#5 /home/www/gnusocial/lib/apiaction.php(288): ApiAction->twitterStatusArray(Object(Notice), false)
#6 /home/www/gnusocial/actions/apisubscriptions.php(214): ApiAction->twitterUserArray(Object(Profile), true)
#7 /home/www/gnusocial/actions/apisubscriptions.php(112): ApiSubscriptionsAction->showProfiles(true)
#8 /home/www/gnusocial/lib/action.php(124): ApiSubscriptionsAction->handle(Array)
#9 /home/www/gnusocial/lib/action.php(101): Action->execute(Array)
#10 [internal function]: Action::run(Array)
#11 /home/www/gnusocial/index.php(316): call_user_func('ApiUserFriendsA...', Array)
#12 /home/www/gnusocial/index.php(330): main()
#13 {main}

**Comment by hannesmannerheim** [comment]
maybe a gnu social bug? quitter.se is running an older gnu social version and the friends list api request works there:

https://quitter.se/api/statuses/friends.json?count=20&screen_name=hannes2peer

but it doesn't on your instance:

https://statusnet.lebegue.org/api/statuses/friends.json?count=20&screen_name=identlud

**Comment by hannesmannerheim** [comment]
doesn't work on .es too https://quitter.es/api/statuses/friends.json?count=20&screen_name=perro

@mmn the above api is broken!

**Comment by llebegue** [comment]
I'm running nightly on GNUSocial and Qvitter

**Comment by mmn** [comment]
I wouldn't recommend running nightly during this weekend :D :D

**Comment by mmn** [comment]
But I'll make sure to fix it and I'll report here in case it can help getting stuff running on other sites since as you mention the API call seems borken.

**Comment by hannesmannerheim** [comment]
ok, this bug makes e.g. this page go blank https://quitter.es/perro/subscriptions

**Comment by mmn** [comment]
Yes, this is an InvalidUrlException which is thrown because we couldn't figure out what "external URL" to return for the Notice. This is the notice that causes the issue for llebegue: https://statusnet.lebegue.org/notice/483087

The exception is thrown at line 546 in QvitterPlugin.php

Just make the call with `->getUrl(true);` to allow a fallback to a local representation (since we don't know how to make a human-available HTTP URL to the remote end).

**Comment by hannesmannerheim** [comment]
has the behaviour of getUrl changed?

**Comment by hannesmannerheim** [comment]
did that solve it @mmn?

**Comment by mmn** [comment]
I think it originally just reported either the 'url' or the 'uri' fields. But as 'uri' may not be an HTTP URL, it should never be used in `<a href="...">` for example. So getUrl() just complains a bit louder so things like these are noticed :D

@hannesmannerheim  And yes, it solved it. :)

**Comment by hannesmannerheim** [comment]
but this seems weird.. external notices should _always_ have an url, no?

**Comment by hannesmannerheim** [comment]
good :)

**Comment by mmn** [comment]
Mye, they probably should. But some things aren't represented visually like that, or at least not linked to. For example a "follow" activity, of course we interpret it locally in some feeds to show it as "X has subscribed to Y", but a representational URL (that you can browse to and "view the activity") is never sent to remote servers afaik. Just the URI, which is used to uniquely identify the activity if it were to be sent multiple times or whatever.

**Comment by mmn** [comment]
I just noticed I caused this error (or as I would call it: discovered this bug through an added feature!), haw haw. https://github.com/mmn/qvitter/commit/b135a51d6a1abb05e5b439496441d09467ca518d

**Comment by hannesmannerheim** [comment]
ahh, now i understand :) a follow doesn't have an url, true!
