### ISSUE TITLE
URL shortener fails to detect certain URLs under certain conditions

### ISSUE THREAD

**Issue by gordon-morehouse** [hannesmannerheim/qvitter#135]
Often, the URL shortener in Qvitter will fail to detect some URLs if they are pasted after a colon. This may happen under other circumstances as well.

In the following screenshot, I've typed ```lol hehe: ``` (including a space after the colon) and then pasted a URL, which is misdetected and does not activate the URL shortener button.

If I add and delete a second space after the colon, or if I delete the colon, the URL will be detected correctly and the shortener button will activate.

![qvitterurl01](https://cloud.githubusercontent.com/assets/304300/6693783/ae7b5bda-cc92-11e4-96e0-833d4cf6b106.png)

**Comment by hannesmannerheim** [comment]
i can reproduce this in safari browser, but not firefox. safari adds a "non breaking space" instead of a regular space after the colon, for some reason. should be easy to fix!

**Comment by hannesmannerheim** [comment]
is it working for you on quitter.se now?

**Comment by gordon-morehouse** [comment]
It failed this morning (on a quitter.se test account) when I pasted a different URL after a quotation mark. The same "add and delete a space" workaround also worked in that case. Now I can't reproduce that bug either, but I hadn't refreshed the browser at that time.

**Comment by hannesmannerheim** [comment]
if you hadn't refreshed that explains it. closing this, but feel free to open it if you see it again!

**Comment by gordon-morehouse** [comment]
Thank you for the fix! :)
