### ISSUE TITLE
[BUG] No refresh if we reply in notifications TL

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#142]
If I receive a notification and I reply it in this TL, the notifications TL doesn't get refreshed anymore.
I use Firefox with: 
- NoScript
- FoxyProxy → TOR
- Privacy Bagder and Cookie Monster for cookies (all allowed)
- Disconnect (browsing)
- Blender
- HTTPS everywhere

I've checked it on Konqueror (no plugins) and I've got no notification after replying in this TL.

**Comment by hannesmannerheim** [comment]
i can reproduce it, thanks!

**Comment by moshpirit** [comment]
Thank you for your work, if I can do anything else, just make me know!

**Comment by hannesmannerheim** [comment]
hopefully i fixed this now. it's live on quitter.se aldready, but not on .es until mmn updates.

**Comment by moshpirit** [comment]
Thank you very much! : )
