### ISSUE TITLE
Unable to delete reply to post in new view

### ISSUE THREAD

**Issue by brocktimusprime** [hannesmannerheim/qvitter#147]
When a user is replying on a post in the new style view, the user has no option to delete the reply. 
In classic view the user can find the same post and has the option to delete it. 

The user does however, have the option to delete her own standalone posts in the new style view.

**Comment by hannesmannerheim** [comment]
hm, you mean when clicking the ellipsis (…) the menu cut off?

**Comment by brocktimusprime** [comment]
When clicking the ellipses it only shows the block original poster. It seems that the menu ends correctly (not being cut off). The person that reply’s gets no option to delete their post form the ellipses. In classic view the trash can does show and it allows the user to delete their reply.

**Comment by hannesmannerheim** [comment]
thanks. i'll check it out later. i think i have seen that happen too

**Comment by brocktimusprime** [comment]
Thanks so much please reach out if any more clarification is needed.

**Comment by hannesmannerheim** [comment]
i hopefully fixed this now. if you encounter it again (after your instance has been updated), please feel free to open this issue again!

**Comment by brocktimusprime** [comment]
Thanks for turning this around so quick. I will verify the issue is resolved.

Thanks

Brock



Sent with Good (www.good.com)


-----Original Message-----
