### ISSUE TITLE
[Bug] !feminism not working in search history

### ISSUE THREAD

**Issue by Cassolotl** [hannesmannerheim/qvitter#148]
I'm not sure if I'm posting this in the right place, so if I'm not just say and I'll try to find the right place!

In my search history on the left, !feminism doesn't show me a nice group page.

![screen shot 2015-03-27 at 07 17 37](https://cloud.githubusercontent.com/assets/6607512/6863910/92dfe53c-d451-11e4-8662-f423a2b69e57.png)

I'm assuming it's because me and !feminism are on different instances (I'm on quitter.se and !feminism is on loadaverage.org).

**Comment by hannesmannerheim** [comment]
you're right, it's because there's no such group on quitter.se. the weird thing is how it got into your browsing history. did you at some point try typing "https://quitter.se/group/feminism" into the location bar?

**Comment by Lottiotta** [comment]
Ah! Yes, I think I did. Okay, so I should delete !feminism from the history, and now you know of a weird bug thing. Thank you for your help!

**Comment by hannesmannerheim** [comment]
yes, thanks!
