### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by jtesse** [hannesmannerheim/qvitter#151]
Hi,

I just git qvitter repository and install it in a fresh install of GnuSocial (1.1.3)
GnuSocial didn't work when I activate Qvitter in config.php
error.log says : 
PHP Fatal error:  Class 'Locale' not found in /my/path/social-mainline/plugins/Qvitter/actions/qvitter.php on line 224

Any idea ? 
Thanks

Jonathan

**Comment by hannesmannerheim** [comment]
do you have the php-intl extension?

**Comment by jtesse** [comment]
Of course not. Sorry for the inconvenience.
It would be a good idea to add the prerequisites in the readme.md ?

Thanks a lot.

**Comment by hannesmannerheim** [comment]
is it not already listed as a prerequisite for gnu social in the INSTALL file?

**Comment by hannesmannerheim** [comment]
(np!)
