### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by brocktimusprime** [hannesmannerheim/qvitter#152]
Feature request please let me know if this is in the pipeline or if other have requested this. Is this possible to make this per-user on/off switch for this feature?

**Comment by moshpirit** [comment]
Qvitter is already auto-refreshed, I don't know what do you mean exactly with "per-user on/off switch" do you mean to manually enable/diable this auto-refresh?

**Comment by hannesmannerheim** [comment]
i don't think i will add this feature. why is it useful? the auto updating is not really annoying, it's very discrete and just adds a small bar with the new notices count in it.

**Comment by moshpirit** [comment]
That's exactly what I thought
