### ISSUE TITLE
Hashtag links with punctuation directly after don't search properly

### ISSUE THREAD

**Issue by Lottiotta** [hannesmannerheim/qvitter#154]
If I type *\#cat.* in a post, clicking the hashtag in the resulting post leads to a search for *\#cat.* rather than *\#cat* (leading to this URL: [https://quitter.se/tag/cat.](https://quitter.se/tag/cat.)

Example post: https://quitter.se/notice/3607717

**Comment by moshpirit** [comment]
I think symbols in hagstags is a good feature, but maybe ".", "," and ";" should be out of these symbols, so I partially agree with you.

**Comment by hannesmannerheim** [comment]
this is how gnu social works. dots are valid characters in hashtags in gnu social. suggest a change to the gnu social developers: https://bugz.foocorp.net/

**Comment by Lottiotta** [comment]
[Done](https://bugz.foocorp.net/T96). :) Thanks for pointing me in the right direction!
