### ISSUE TITLE
File attachment fails sometimes

### ISSUE THREAD

**Issue by Lottiotta** [hannesmannerheim/qvitter#155]
If I try to attach an image:

![screen shot 2015-04-05 at 11 50 05](https://cloud.githubusercontent.com/assets/6607512/6996597/fba5b62a-db89-11e4-9061-d5302ab715da.png)

And then I click the cross in the top right corner to cancel it before it's complete, images won't attach after that (unless I hard-refresh); it gets stuck on this:

![screen shot 2015-04-05 at 11 51 27](https://cloud.githubusercontent.com/assets/6607512/6996600/1e31d57a-db8a-11e4-8a6b-f30ca23cd6e2.png)

**Comment by hannesmannerheim** [comment]
i can't reproduce this in firefox 36. which browser are you using?

**Comment by Lottiotta** [comment]
Chrome Version 41.0.2272.118 (64-bit).

**Comment by knuthollund** [comment]
NB: there seems to be an issue with images attached to a reply-notice in the latest gnusocial master code. Don't know if q.se is using this version. (I've got this issue on gnusocial.no now)

**Comment by mmn** [comment]
@knuthollund that was the same issue we solved earlier today right? (it wasn't in the qvitter interface, so it reasonably cannot be related to this :P)

**Comment by knuthollund** [comment]
Yes @mmn , I think it is the same issue.

**Comment by hannesmannerheim** [comment]
@Lottiotta i can't reproduce it in chrome either

**Comment by Lottiotta** [comment]
@hannesmannerheim Hm! Okay, I'll try again and if it's still a problem I'll write the steps down here, but if it's just me that experiences it then cool.

Nope, seems to be gone - but it's doing a weird double-attach thing and it's trying to attach files even when I press cancel! I don't know, I'm going to close this and report again when the bug is more consistent and replicable. :)
