### ISSUE TITLE
Replies enhancement

### ISSUE THREAD

**Issue by Cassolotl** [hannesmannerheim/qvitter#157]
Currently, if someone sends a post to me I get a blue "1" next to "Notifications" on the left. If I reply to that message in "Timeline" (without clicking "Notifications"), that blue "1" doesn't disappear. I have to view Notifications to make the "1" go away, even though I have already replied to the message.

I would like it if replying to a message @-me in "Timeline" removed the blue "1" notification indicator, so that I did not have to needlessly click over to Notifications to get it to go away.

**Comment by moshpirit** [comment]
I've been thinking in suggest this exactly thing a few hours before. :+1:

**Comment by brocktimusprime** [comment]
+1
