### ISSUE TITLE
PHP Fatal error:  Class 'Locale' not found

### ISSUE THREAD

**Issue by merolhack** [hannesmannerheim/qvitter#158]
GNU social 1.1.3 (February 2015-02-27)
PHP Version 5.4.16
Apache 2.4.6
CentOs 7

[:error] PHP Fatal error:  Class 'Locale' not found in /var/www/html/plugins/Qvitter/actions/qvitter.php on line 224
[:error] PHP Stack trace:
[:error] PHP   1. {main}() /var/www/html/index.php:0
[:error] PHP   2. main() /var/www/html/index.php:330
[:error] PHP   3. call_user_func:{/var/www/html/index.php:316}() /var/www/html/index.php:316
[:error] PHP   4. Action::run() /var/www/html/index.php:316
[:error] PHP   5. Action->execute() /var/www/html/lib/action.php:101
[:error] PHP   6. QvitterAction->handle() /var/www/html/lib/action.php:123
[:error] PHP   7. QvitterAction->showQvitter() /var/www/html/plugins/Qvitter/actions/qvitter.php:57

**Comment by hannesmannerheim** [comment]
the extension php-intl is required for gnusocial, and also qvitter.
