### ISSUE TITLE
Direct acces to the messages in the avatar menu

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#159]
I know you have in mind to implement direct/private messages in Qvitter but, for now,  think it would be a good idea to have a direct access to them in what I called "the avatar menu". This menu it's the one shown when we pushed our profile picture in the top bar, so it should be something like this: 

![instantanea45](https://cloud.githubusercontent.com/assets/7888062/7032133/e5965496-dd70-11e4-821f-ad2af194a0ae.png)

Since a lot of users unknown how to send private messages, I think it could be a good way to let them know how (even if it's a temporally solution).

The link would be something like: [Messages](https://quitter.es/username/inbox) for the user "username".

**Edit**: it could be named "Messages", "Private messages", "Direct messages" or similar.

**Comment by hannesmannerheim** [comment]
i'm reluctant... i don't really want to advertise it since i think the dm feature is broken because it's not federated. also i don't want to mix the qvitter interface with the default interface too much.

**Comment by moshpirit** [comment]
Not federated? o.O

OK, I understand the UIs mix :+1:

**Comment by hannesmannerheim** [comment]
yes, sadly you can't sent private messages to another instance yet. advertising the feature could hinder federation, people might want to register on the same instance to be able to dm eachother. so i don't want to add it to qvitter until dm:s federate like they should.

**Comment by moshpirit** [comment]
Hmm I didn't know that, thanks for the explanation. And as I've seen, we can't share private notes to just a contact, but a group or all our "friends". If we could, that would be something as simple as a "private note" mentioning this user (or users) : )

**Comment by hannesmannerheim** [comment]
that would be a gnusocial feature request. 

but i don't know if the private "locked" notices are really private in gnusocial though. the feature wasn't working properly when i tried it last time. it's another half baked feature that should be fixed and made intuitive or removed completely, in my opinion.

**Comment by moshpirit** [comment]
[Requested](https://bugz.foocorp.net/T99)
