### ISSUE TITLE
All the languages using capital letters

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#160]
In the "avatar menu" (the one shown when we pushed our profile picture in the top bar), some of the languages use capital letters (upper case/title case, as you prefer), so I think they all should use the same case.

e.g:  
**E**nglish / **e**spañol  ──[should be]→ **E**nglish / **E**spañol

**Comment by hannesmannerheim** [comment]
i'm not a fan of that... i think it's better to respect the language capitalization rules. e.g. in swedish you don't capitalize languages.  "Svenska" looks ugly to me. i would agree if all languages were written in their english names.

**Comment by moshpirit** [comment]
Not even if you have to list it? I mean, this is a list of languages, I think that the best way it's using capital letters, just like we use:
- العربية
- Asturian
- Català
- Deutsch
- English
- Esperanto
- Español (**latino**)
- Español
- Euskara
- فارسی
- Suomi
- Français
- Galego
- Italiano
- Norsk
- Português (Brasil)
- Svenska
- 中文 (中国)
- 中文 (台灣)

Instead of: 

- العربية
- Asturian
- català
- Deutsch
- English
- esperanto
- español (**latino**)
- español
- euskara
- فارسی
- suomi
- français
- galego
- italiano
- norsk
- português (Brasil)
- svenska
- 中文 (中国)
- 中文 (台灣)

BTW, I've seen that it uses "ahorita" instead of "latino". "Ahorita" it's a diminutive of "Ahora" ("Now" in English) and it's mostly used in Latino Spanish.

**Comment by hannesmannerheim** [comment]
ahorita is a joke/meme language, created because when ahorita was corrected to ahora in the spanish translation, lots of quitter.es users wanted it back.

and no, lists in swedish are not capitalized. i don't know about other languages, but anyhow my guess is that it's easier for people to find their language in the list if it's written in the usual way. also capitalizing other language names feels somewhat "imperialistic" to me, forcing english language rules upon other languages.

**Comment by moshpirit** [comment]
Hmm OK, then, I'd like you to capitalize Español, Galego and Catalán. I think they're capitalized in lists. Anyway, I've been searching any list with any language using small case and I've found just five in the Diaspora settings. 

These services uses capitalized lists with all the languages:

- Android languages for the input method
- [Wikipedia](https://www.wikipedia.org/)
- [Twitter](https://twitter.com/)
- [StartPage](https://startpage.com/do/preferences.pl)
- [openSUSE](https://www.opensuse.org/en/)
- [Prism-break](https://prism-break.org/en/)

**Comment by hannesmannerheim** [comment]
since it's done by programming not hardcoding, it's either capitalizing all languages or only those who are always capitalized by rule (supplied by the php-intl module). so i'm keeping it as is.
