### ISSUE TITLE
Suggest the groups we are joined in when we're writing

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#162]
Sometimes, we post groups thinking that we've already joined in, but then, we realised that, we're not once it's already published. That can be fixed suggesting groups too, because that way if we write the name of a group and it's not suggested: or we're not joined in or we've written the group wrong so: double win! :+1:

**Comment by hannesmannerheim** [comment]
thanks. been planning this but it has been forgotten

**Comment by Cassolotl** [comment]
I like this idea. :)

**Comment by hannesmannerheim** [comment]
fixed now

**Comment by moshpirit** [comment]
\o/ woohoo thanks!!
