### ISSUE TITLE
Enlarge shorted URLs of pictures

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#163]
See [this notice](https://quitter.es/notice/325428) for more information.

**The problem**: external pictures aren't showed if they're shortened. In the other hand, there are some instances (like quitter.se) that allows a very limited number of characters so an external picture can use even more chars that which are allowed.

**The solution**: create some way to enlarge and show these URLs when the post is published, that way we can use the shorter and see the thumbnails.

**Comment by hannesmannerheim** [comment]
this might be a quitter.es issue, but i'm not sure. @mmn: shouldn't quitter.es try to look up the final url of a shortened link, and add it in the title attribute in the rendered notice html?

**Comment by mmn** [comment]
Maybe so, but the title attribute shouldn't be a URL if there is an actual title (which is the case for oEmbed lookups). But I guess neither of those work properly. Whether it's an image or not should be in a mimetype attribute or something.

Nonetheless, yes it is GNU social's responsibility to try to find the canonical URL and store the initial and final referral data. So I don't think this is a qvitter bug (except perhaps that it is written to work with bad output which is generated by GNU social :))

**Comment by hannesmannerheim** [comment]
yes, it would be awesome if the looked up final url:s were added as separate attachment metadata in the api response :)

**Comment by hannesmannerheim** [comment]
and if the final url after all redirects is an image, a generated thumbnail would be even more awesome :))
