### ISSUE TITLE
Group view show the other nicknames of the groups above/below the bio

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#164]
I'd like to see the other nicknames of the groups above/below the bio of the groups

e.g:
 
!blackmetal@status.vinilox.eu → name of the group
http://qttr.at/oyt → link
black metal ist krieg → bio
!bm, !black → other nicknames to name the group

**Comment by hannesmannerheim** [comment]
for future reference: replied here: https://quitter.se/notice/3682690
