### ISSUE TITLE
only topbar visible if DOM storage disabled

### ISSUE THREAD

**Issue by wiewo** [hannesmannerheim/qvitter#165]
Thank you for your work on the project!
Normally, I have DOM storage disabled in firefox. When I am browsing any of the quitter instances, only the the topbar is displayed and a blank page otherwise. It looks like the ```checkLocalStorage()``` function gets called and does not terminate. With DOM storage enabled, everything works fine.
Is the DOM storage a hard requirement or could the interface work without it, at least for browsing without logging in?

**Comment by hannesmannerheim** [comment]
no your right, it should work without. i've just not prioritized it since not many have localstorage disabled. but it's definitely a bug! thanks!
