### ISSUE TITLE
User history

### ISSUE THREAD

**Issue by brocktimusprime** [hannesmannerheim/qvitter#167]
When you click on a person it takes you back to “classic”.  Support in Qvitter for Profiles and user tweet history.

**Comment by hannesmannerheim** [comment]
can you explain more? when you click on a user where?

**Comment by brocktimusprime** [comment]
When clicking on a username from a feed.

**Comment by hannesmannerheim** [comment]
then you should not be taken to classic. which instance are you on and what user are you clicking?

**Comment by brocktimusprime** [comment]
i am on version 4 i am clicking on any user

**Comment by hannesmannerheim** [comment]
i can't replicate that

**Comment by brocktimusprime** [comment]
Seems to be and issue on our end.  out url url is tweet.peak6.net when i click on user name from the feed the url then opens to tweet/username
