### ISSUE TITLE
rss to quitter

### ISSUE THREAD

**Issue by phls** [hannesmannerheim/qvitter#171]
Hi,

Do you know If there is a way to get feed rss and send to quitter.se?
I use dlvr.it to send to twitter, but I didn't find any tools to do that using quitter.

Thanks,

**Comment by hannesmannerheim** [comment]
try asking in the !gnusocial group. 

(if you have control over the rss feed you can "push enable" it, or something like that, which makes it possible to subscribe to. i don't know exactly how to do that though. if it's a wordpress feed you can install a wp plugin that auto posts to gnusocail)

**Comment by phls** [comment]
Ok. I saw the mirror plugin is not installed at quitter.se. Do you pretend install it?

**Comment by hannesmannerheim** [comment]
no i don't think we will install that on quitter.se. it's better if feeds tell quitter when they are updated, than quitter having to poll lots of feeds.

**Comment by phls** [comment]
Hi, do you know why I can't connect dlvr.it to quitter.se? I managed to connect rss from dlvr.it to status.vinilox.eu, but when I try to connect to quitter.se, I can't.

**Comment by hannesmannerheim** [comment]
no idea, never tried it

**Comment by phls** [comment]
Hi, can you tell me what hardware and bandwidth are you using in the server? I saw you bought new hardware some months ago. I'm researching the necessary hardware to have a server.

**Comment by hannesmannerheim** [comment]
we have 100 mbit connection and a few gigs of ram. but we don't use all the megabits and we have lots of other stuff on our server too. i don't think you need very much when you are starting a new server. i've seen instances run on raspberry pies. when the site start getting slow, try allocating memory to mysql and processor to queuedaemon. only upgrade the server if that doesn't help.
