### ISSUE TITLE
Show the number of Replies/Repetitions/FAVs directly in the timeline

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#172]
That would make that the best comments more visible to the users.

I've made this simulation and highlighting the colour of the icons that has been interacted by the users:

![simulation](https://cloud.githubusercontent.com/assets/7888062/7598566/acfae9f4-f8ea-11e4-99db-6c11769cafac.png)

The colours would change if we are one of the users that interact with this message. That way the "Repetition" icon would be green, the "Mark as favourite" would be yellow and I think that the colour of the "Replies" could be blue or maybe it could depends of the background colour, I don't mind.

**Comment by hannesmannerheim** [comment]
fixed in e3da8af8e2fb824d357ade136ecb1e31b307201c

i decided not to add replies number because there's no support in gnusocial code for this, and it would potentially be resource draining to generate this number.

**Comment by moshpirit** [comment]
OK thanks anyway :-)
