### ISSUE TITLE
Editing posts

### ISSUE THREAD

**Issue by ericlevin** [hannesmannerheim/qvitter#173]
Is there an easy way to edit a post?  I frequently will want to go back and fix a #hashtag or a mis-spelling.  I don't seem to be able to.  I can delete - but not edit.

Perhaps make this an admin feature if there is some concern with allowing users to edit their posts?

**Comment by hannesmannerheim** [comment]
there's no support in gnu social for editing notices, and it would require an extension to the ostatus protocol, so it's not something that is easy to implement.

**Comment by Cassolotl** [comment]
How about similar to the gmail feature of the sending of an email being delayed, so you can cancel the sending and edit your email again?

So you write a post, click post, and then Qvitter "holds" it for a minute or so, and shows you an edit button for that minute. And then at the end of the minute, the edit button disappears and Qvitter publishes the post.

**Comment by hannesmannerheim** [comment]
this will probably never happen, so closing it.
