### ISSUE TITLE
Repeated notifications

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#174]
I've noticed that I'm receiving more notifications than what I should get (like I do in the classic interface) with some messages.

4 examples: 

- [Case 1](https://quitter.es/notice/376960)
- [Case 2](https://quitter.es/notice/376951)
- [Case 3](https://quitter.es/notice/376976)
- [Case 4](https://quitter.es/notice/376968)

**Edit**: OK, I'm receiving these and the next notifications for this conversations twice.

**Edit 2**: it has stopped and everything works great again. ...For now.

**Comment by hannesmannerheim** [comment]
it looks like this is because your username is mentioned twice in the notice text. thanks for reporting it!

**Comment by moshpirit** [comment]
Thank you for fixing it! :-)
