### ISSUE TITLE
Copying #, ! and @

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#179]
When I copy some note (maybe to share it on any other social network, I can't copy the symbols used for tags, groups and mentions: "#", "!" and "@". Sometimes it's a bit annoying to write all of them. It would be cool if we could copy/paste them (as we do on Twitter and Diaspora).

**Comment by hannesmannerheim** [comment]
this has to do with better rtl-support. @ and # and ! are removed from the html and added as pseudo objects with css. it could be enhanced so that it only does it when an rtl language is selected.
