### ISSUE TITLE
Site background image appears only after login out

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#182]
When accessing the home page the site background image is not displayed :
`<body class="" style="background-color: rgb(244, 244, 244); background-image: url(&quot;&quot;);">						`

After login out the body html tag is ok :
`<body class="" style="background-color: rgb(244, 244, 244); background-image: url(&quot;https://statusnet.lebegue.org/local/plugins/Qvitter/img/lebegue.org.bass.background.png&quot;);">`

It should be displayed when accessing the home page

**Comment by hannesmannerheim** [comment]
i'm not entirely sure what you mean, but i see the background image without logging in 
![skarmavbild 2015-06-04 kl 08 50 42](https://cloud.githubusercontent.com/assets/2437812/7978563/e8ffa0c6-0a96-11e5-8b43-3a055c887a99.png)

**Comment by hannesmannerheim** [comment]
oh, sorry, i read wrong, you mean you want the default background to show when you're logged in? that's not how qvitter is intended to work. instead, users can upload their personal background image when editing their profiles.

**Comment by llebegue** [comment]
I realized that I needed to open my eyes better in the morning.

My shortcut in firefox is "https://statusnet.lebegue.org/identlud" . That's not the home page but my profile ... and my profile is NOT configured with a background.

There's nothing wrong with qvitter ! I'll go and consult a doctor ...
