### ISSUE TITLE
Long postings (from Friendica) can't be expanded

### ISSUE THREAD

**Issue by annando** [hannesmannerheim/qvitter#184]
Example: https://quitter.se/notice/3771299

When I click on the three dots then nothing is happening. Now the question is:

* Is it a problem that occurs with every long post
* Is it a problem that occurs only with posts from Friendica

Currently I'm working at the OStatus protocol part at Friendica. I'm trying to make it more compatible with GS. So if I can do anything to make it more compatible, please tell.

**Comment by hannesmannerheim** [comment]
i don't think any oversized notices can be loaded when logged out. it's not just friendica ones. try https://quitter.se/main/all and you'll see. the api doesn't allow it, but maybe it should. 

that api was an qvitter specific api before, but it has made it into gnu social core now, so i think it's better send this as a feature request to gnu social.

**Comment by hannesmannerheim** [comment]
but friendica support is not 100% in qvitter though, e.g. previewing "profile cards". i'll look into that.

**Comment by annando** [comment]
If the loading of oversized posts is working when logged in, then I'm satisfied.

And: Whenever you would need to change something in qvitter for Friendica then tell me before you change it, so I could change it in Friendica.

**Comment by annando** [comment]
Just another (off topic) question: As I said, I'm working at the whole protocol stuff. My problem is that my whole work is now based on trial and error and trying to understand the GNU Social code.

My current problem is delivering comments to people that I follow but who don't follow me and who are on servers where I don't have any followers. It seems GS is able to do it - but I really don't know how.

Question is: Is there any place where I find the right people to answer my questions?

**Comment by hannesmannerheim** [comment]
maybe @mmn knows

**Comment by mmn** [comment]
There are some weird cases in handling the "too long notice" things. Some kinks are worked out reltaively recent, some not. One major issue is that if I write a notice on my 1000 character site, someone reads it on 140 char quitter.se and then repeats it - a third party might get it in 140 char format with an attachment URL to _quitter.se_.

I don't think that's it in this case, though, but I do believe the error is on the receiving side (GNU social on quitter.se) for shortening the rendered queet and then having trouble with the attachment.

From Friendica's side you shouldn't have to pay any respect to the receiving site's max notice length. Just send what you've got in <entry><content type="html">[...]</content>... and whatever filtering or stripping or shortening should be done on the receiving side.

**Comment by hannesmannerheim** [comment]
@mmn i was referring to the "Just another (off topic) question"...

**Comment by mmn** [comment]
@hannesmannerheim Sorry, I'll answer that too :dancer: 
@annando the Salmon protocol is used to send notifications to anyone regardless if they're a subscriber or not. I have no idea what happens to the Google Code silo in the coming months, as it's shutting down, but here's the specification for Salmon: https://salmon-protocol.googlecode.com/svn/trunk/draft-panzer-salmon-00.html

**Comment by annando** [comment]
@mmn Thanks! There is already an existing salmon implementation in Friendica - but my last tests weren't successful so I focused on pubsub - which worked well (for subscribers).

So I will compare the specification with the existing code. All I know by now is that there is a signature problem. But since I know now that there isn't any third protocol, I will focus on this one. Thanks!

But returning to what I'm sending from Friendica: Today I changed the export so that link descriptions are exported as well: https://pirati.cc/notice/112665

GS and SN have no problems with this. I don't know what Qvitter is doing. And I haven't tested by now with many mobile applications. AndStatus will work since it supports HTML. But I'm unsure about Mustard. "Zwitscher" is failing. Twidere has other issues, I guess. (At Friendica I'm constantly adding new functions to the API to maintain the Twidere support)

**Comment by hannesmannerheim** [comment]
looks fine on quitter.se

![skarmavbild 2015-06-06 kl 18 17 11](https://cloud.githubusercontent.com/assets/2437812/8020427/51180e7c-0c78-11e5-8762-12bfab3c6cbe.png)

**Comment by hannesmannerheim** [comment]
can i close this, or is there any unresolved issues regarding Qvitter still?

**Comment by annando** [comment]
Since there seems to be no problems with Friendica posts in the Qvitter environment, this issue can be closed.
