### ISSUE TITLE
Misaligned spritemap or logo in mobile view

### ISSUE THREAD

**Issue by mmn** [hannesmannerheim/qvitter#186]
Lower resolution screens where Qvitter enters some sort of "mobile view" have an issue with the logo on top, introduced since commit 9e45bcab4732806d291d2326e2f8a5d676caf0df

It looks fine in desktop view, but this is what mobile view gives me (this is social.umeahackerspace.se - same behaviour on quitter.es - and on quitter.se there's no logo there at all):

<img src="http://h45h.com/5Q154K7NQdghjmODF-fR-4NhjeqSDNL4BDuS8ISMsgg=" alt="mobile view bug for Qvitter logo"/>

<i>Btw, the blue circle without an indication on the amounts of notifications I have is not related (that's because I have ~950 unread notices from ages ago that I haven't scrolled down to nor reset manually).</i>

**Comment by hannesmannerheim** [comment]
thanks!
