### ISSUE TITLE
thumb_url - not defined in the array (index)

### ISSUE THREAD

**Issue by abjectio** [hannesmannerheim/qvitter#190]
Experience some of this error  ...: 

2015/06/13 11:01:34 [error] 2449#0: *259 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: thumb_url in QvitterPlugin.php on line 455" while reading response header from upstream, client: 83.252.137.154, server: quitter.no, request: "GET /api/statuses/public_and_external_timeline.json?t=1434186147946 HTTP/1.1", upstream: "fastcgi://unix:/run/php5-fpm.sock:", host: "quitter.no", referrer: "https://quitter.no/main/all"

**Comment by abjectio** [comment]
Is the withspaces a result of the error above? Don't find it very attractive to have such large whitespaces in the feed ... :/ 
![jutjube](https://cloud.githubusercontent.com/assets/3600521/8145486/e0bf3168-1209-11e5-89e5-e10377a476f7.jpg)

**Comment by hannesmannerheim** [comment]
it seems newer gnusocial doesn't serve the thumbnail urls for youtube videos anymore...

**Comment by hannesmannerheim** [comment]
i've created a "release" of qvitter a couple of weeks ago that is reasonably stable, the master branch will probably be buggy in the future, since a lot of new features are coming.

**Comment by hannesmannerheim** [comment]
i think the plan is to either override this new gnusocial behaviour, or save the youtube thumbnails locally.

**Comment by abjectio** [comment]
ok - tx.

**Comment by moshpirit** [comment]
I was going to report the same error. The thumbnail come but after a while! (maybe 1 minute) so the thing is fixing this time : )

Thanks for the work!

**Comment by moshpirit** [comment]
Oh, and BTW, the videos appear in the inverse order to the posted one. I mean, if I post two videos A and B, they appear in this order: B A 

[See this example with 6 videos](https://quitter.es/notice/424486): A, B, C, D, E and F. Qvitter shows this:   
note  
F 
E 
D 
C 
B 
A

**Comment by hannesmannerheim** [comment]
@abjectio i was wrong, gnusocial still creates thumbnails, it was a pure qvitter bug. fixed in latest commit.

still keeping this open though, so i remember to fix @moshpirit's issue.

**Comment by moshpirit** [comment]
Great, thanks!

**Comment by abjectio** [comment]
Ahh - ok @hannesmannerheim - tx for fix.
