### ISSUE TITLE
Cannot go back to a group's timeline

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#196]
1. Go to https://quitter.no/group/lernezido/members
2. Try to go back to the timeline (https://quitter.no/group/lernezido).

My suggestion: make the group name (e.g. "Lernez Ido!") a clickable link that redirects to the group's timeline.

**Comment by hannesmannerheim** [comment]
fixed in https://github.com/hannesmannerheim/qvitter/commit/df99f9bbaa83b10a1e1cc27e9b33ca81db74fa4f
