### ISSUE TITLE
Mouse problems: when I click, the writter goes to the beginning 

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#203]
I noticed that when I reply something or write a new note using the popup box to enter the text and I click on any word, the write line moves to the beginning of the text: 

![instantanea4](https://cloud.githubusercontent.com/assets/7888062/8231741/e5c7ba4e-15ca-11e5-9163-7fe9a1cee686.png)

I didn't report it yet because I though it was a KDE SC error (I'm using the last version of Plasma) but another user reported me the same error, so I think that this is a popup bug.

**Comment by hannesmannerheim** [comment]
yep, i know about it. but good that you brought it up here too. 

more: https://quitter.se/notice/3787250

**Comment by hannesmannerheim** [comment]
i went crazy trying to fix this, but could find the problem. but now it has been mysteriously fixed by itself... is it just me, or does it work for you too @moshpirit?

**Comment by moshpirit** [comment]
It is in my quitter.se account!! thanks!! \o/

**Comment by hannesmannerheim** [comment]
great!
