### ISSUE TITLE
[Language Menu] Add U+200E LEFT-TO-RIGHT MARK character after U+0029 RIGHT PARENTHESIS

### ISSUE THREAD

**Issue by GreenLunar** [hannesmannerheim/qvitter#205]
Add `&lrm;` tag after `)` to avoid `português (Brasil)` being displayed like this `(português (Brasil`.

**Comment by hannesmannerheim** [comment]
hm, it's not displayed like that when i select a RTL language. is there's a browser setting that makes this happen?

**Comment by GreenLunar** [comment]
No, this is what happens when you have a neutral character (character that has no direction set) at the end of a string, and for these cases you have Unicode Control Characters such as LRM (that is, U+200E LEFT-TO-RIGHT).

**Comment by GreenLunar** [comment]
Did you open Language Menu in RTL locale?

**Comment by hannesmannerheim** [comment]
yes

**Comment by hannesmannerheim** [comment]
![skarmavbild 2015-06-18 kl 17 51 52](https://cloud.githubusercontent.com/assets/2437812/8235522/cacda1d2-15e2-11e5-8d30-07934e3182a5.png)

**Comment by hannesmannerheim** [comment]
would be interesting to know what browser setting that causes it

**Comment by GreenLunar** [comment]
I am using gecko-engine.

![bad_right_parenthesis](https://cloud.githubusercontent.com/assets/2053884/8235559/573137e4-15eb-11e5-8fa5-239da7e71029.png)

**Comment by GreenLunar** [comment]
> would be interesting to know what browser setting that causes it

Maybe it is fixed in latest git version?

**Comment by hannesmannerheim** [comment]
no, i just tried it on quitter.se and it's the same

**Comment by GreenLunar** [comment]
AHA! That menu direction is LTR. I see that `!` is misplaced, `הזמינו חברים!` instead of `!הזמינו חברים`.

**Comment by GreenLunar** [comment]
AHA! That menu direction is always set to LTR. I see that `!` is misplaced, `הזמינו חברים!` instead of `!הזמינו חברים`.

**Comment by GreenLunar** [comment]
I can add `&rlm;` in translation file instead.

**Comment by GreenLunar** [comment]
Also `@` `hannes@` instead of `@hannes`.

**Comment by hannesmannerheim** [comment]
quitter.se is updated with latest qvitter btw

**Comment by GreenLunar** [comment]
> no, i just tried it on quitter.se and it's the same

You must be logged out.

**Comment by hannesmannerheim** [comment]
yes! now i see it!

**Comment by GreenLunar** [comment]
I prefer this menu to follow page direction rather than always being in LTR direction.
