### ISSUE TITLE
Page /subscriptions says Go to original notice, instead of page

### ISSUE THREAD

**Issue by GreenLunar** [hannesmannerheim/qvitter#211]
The links at `/subscriptions` are directing to original user page.

A new string should be added for entries in `/subscriptions` page.

**Comment by GreenLunar** [comment]
Why not "Go to the user's profile" (without "remote")?

**Comment by hannesmannerheim** [comment]
no reason, just edit the language file and change it to whatever you like!

**Comment by hannesmannerheim** [comment]
but, well, the reason is that the text only appears if the user is on a remote instance, and the user might want to know they'll be taken to a remote location when clicking.

**Comment by GreenLunar** [comment]
You can write a specific warning message/popup that would indicate that link is of a remote instance, be it of a profile page a notice or anything else.

**Comment by hannesmannerheim** [comment]
this is what this text string _is_, a small "warning" icon telling the user that it is a remote user, and the text is the hover message when hovering the "warning" icon.
