### ISSUE TITLE
Use Weblate as translatiion platform

### ISSUE THREAD

**Issue by GreenLunar** [hannesmannerheim/qvitter#214]
CopyQ, Exaile, Money Manager EX and even Gammu are currently being translated at https://hosted.weblate.org/ using [Weblate](http://weblate.org/) which provides integration with Git.

It would be easier to me and to other non experienced git users to provide up to date translations to Qvitter.

**Comment by hannesmannerheim** [comment]
sorry for not answering quickly. i looked at that website now and i feel it's too much hassle. i didn't quite understand how to implement it actually, and i think there are other priorities. i think translation is pretty easy with locale-folder here on github, but maybe i should add to the readme how to add a language!

**Comment by hannesmannerheim** [comment]
i added info about translation in the wiki. closing this for now

**Comment by GreenLunar** [comment]
> i feel it's too much hassle.

I will try to handle it, if you would allow me.

@nijel, how difficult would it be to add project qvitter (GNU Social add-on) to a Weblate instance?

**Comment by hannesmannerheim** [comment]
but i would have to get my head around it at least, and it's not a priority for me to spend time trying to understand if weblate is something i want in the project or not. i don't see what problem it is solving really.

**Comment by nijel** [comment]
Once setup, it should need no maintenance (given that you allow it to push to your repository). See https://docs.weblate.org/en/latest/admin/continuous.html for some information on this topic...
