### ISSUE TITLE
Profile resume in The Whole Known Network

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#216]
Sometimes the The Whole Known Network is shown as our profile TL but showing the TWKN TL. I mean:

It shows our profile resume/popup over the TL. There's no problem with the TL itself, but it shows this resume and it not meant to be this way.

I've just changed the language to English in order to share a screenshot, but looks like it somehow "fixed". I changed it back to Spanish but I can't see error again.

Sorry if I didn't explain myself correctly

**Comment by hannesmannerheim** [comment]
i've never seen that happen myself, so it's pretty impossible to fix unless you find out a way to make the bug appear again

**Comment by moshpirit** [comment]
I'll share you a screenshot the next time I'll see it and try to figure out when is happening

**Comment by hannesmannerheim** [comment]
thanks

**Comment by hannesmannerheim** [comment]
i've seen this happen one time now! i think it might have to do when you change streams really fast. i'll see if i can find a way to trigger it more consistently (so i can fix it)

**Comment by moshpirit** [comment]
Good, thank you!!

**Comment by hannesmannerheim** [comment]
yes. click the queet-number in the top left box, then quickly quickly press TWKN or another stream, then the profile card/resume/summary sticks on top
