### ISSUE TITLE
[REQUEST] Please add shortcut write and send a dent

### ISSUE THREAD

**Issue by Turbito** [hannesmannerheim/qvitter#217]
It'd nice a shortcut like "n" to open the dent writer and "ctrl-n" to send it.
Is very confortable to write a serie of dents.
Please consider it

**Comment by hannesmannerheim** [comment]
actually we had this feature before, it was issue #2. but it got removed when I switched to an all new input box. before it was ctrl+enter to post, is ctrl-n better? or both maybe?

**Comment by Turbito** [comment]
Both are nice, i dont mind which shortcut to use.
In twitter is used shortcut ctrl-n, i think it'd be a little more familiar to users that migrate from there

**Comment by hannesmannerheim** [comment]
i checked on twitter, and they use ctrl+n to open a new input box and ctrl/cmd + enter to send it, so i went with that. also implemented a few other shortcuts in a13ccd7ca1d06ba9c3faab97d84b38ca4f0a831d
