### ISSUE TITLE
Qvitter does not save the language preference

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#219]
Even though I log into my account on Quitter.no, the language of the UI is still English while I had previously chosen Ido.

**Comment by hannesmannerheim** [comment]
it because it saves the language per-user, and "logged out" is counted as it's own user. but i'm going to think of a way to make this more intuitive. thanks!

**Comment by hannesmannerheim** [comment]
i think i solved this in a intuitive way. it's live now on quitter.se. but you may have to clear the localStorage in your browser to see it work as intended, which can be a little tricky

**Comment by maliktunga** [comment]
Is the language setting stored locally or on the server? I use Private Browsing on Firefox and it does not switch to Ido when I log in.

**Comment by hannesmannerheim** [comment]
works for me with firefox private window also  (on .se)

**Comment by hannesmannerheim** [comment]
but again, you might have to clear the localStorage for this to take effect

**Comment by hannesmannerheim** [comment]
but if you have some other browser plugin that disabled localStorage, language selection, and a lot of other qvitter features will not work

**Comment by hannesmannerheim** [comment]
(sorry, to answer your question: it's stored locally, in localStorage)

**Comment by maliktunga** [comment]
Wouldn't it be better saved on the server? That way the language would be the same for the user, whatever the browser or computer used. I think that is Twitter's behavior too.

**Comment by hannesmannerheim** [comment]
there's no support in the gnusocial api for that, we'd have to create a qvitter-specific api which is a little work. also i don't see the point, localstorage is working well, and is needed for a lot of other vital qvitter features too.

**Comment by maliktunga** [comment]
Because of that, language switching does not work in Private mode on Mobile Safari.

**Comment by hannesmannerheim** [comment]
not on desktop safari's private mode either apparently

**Comment by maliktunga** [comment]
That's an issue, isn't it? I and other people I know use Private browsing frequently, especially when using someone else's computer.

**Comment by hannesmannerheim** [comment]
although people don't expect webpages to work flawlessly with private browsing, so it's not a big issue for me. i think this is more of an issue with safari being overly paraniod than with qvitter. remember firefox allow localstorage in private windows. i really like localstorage for privacy reasons _just because_ it means we can deal with stuff locally that the server and the middlemen don't have to know about.

**Comment by hannesmannerheim** [comment]
although i may implement an error messaging feature that tells the user that localstorage wasn't available and that that will disable a lot of qvitter features

**Comment by maliktunga** [comment]
What are those Qvitter features that use localstorage?

**Comment by hannesmannerheim** [comment]
caching, speeding up the ui and taking load off the server
