### ISSUE TITLE
"Keyboard shortcuts" localization not effective

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#221]
Even though I translated the "Keyboard shortcuts" string for Ido, it is still displayed in English in the menu. Also, the pop-up window itself is not localized.

**Comment by hannesmannerheim** [comment]
i've not updated quitter.se with that yet

**Comment by hannesmannerheim** [comment]
uploaded the new ido translation now.

**Comment by maliktunga** [comment]
Thank you. The keyboard shortcuts themselves are not localized though. Should I create another Issue about that?

**Comment by hannesmannerheim** [comment]
they are localized by adding files in in the /doc-folder. i've created a file that you can edit

**Comment by hannesmannerheim** [comment]
https://github.com/hannesmannerheim/qvitter/blob/master/doc/ido/shortcuts.html

**Comment by maliktunga** [comment]
Thank you!
