### ISSUE TITLE
Twitter integration

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#227]
AFAIK only Quitter.se has the Twitter bridge and I think I remember reading that it doesn't work properly. That made me think that some applications for Twitter like Twidere allows us to post using more than one account in the same time. That way the user can select with what account wants he post the note. 

Since Qvitter is a webclient for gnusocial, it could ask Twitter to use it as a Twitter client also. So,that way, Qvitter could interact with Twitter in order to copy the note and post it on Twitter also or even use it as a normal Twitter client (which is not my main point and it would mean a lot of more code, so not really a priority).

Maybe that's crazy, but I wanted to know if it's possible, if so, the Twitter bridge could be obsolete after including this feature. 

In fact, I think that most of the people who singed up on January would stayed because of this feature. I know that's a lot of work, so if you get it, I'll donate some money :)

![instantanea8](https://cloud.githubusercontent.com/assets/7888062/8568551/e8c3557e-256e-11e5-9742-d3a85e1ef955.png)

**Comment by hannesmannerheim** [comment]
twitter bridge works on quitter.se, as far as i know, and if it doesn't it's much easier to fix that plugin than to write a new twitter bridge for qvitter. 

in what way is twitter bridge on quitter.se not working?

**Comment by moshpirit** [comment]
I understand, but it's only applied to quitter.se and I have no idea since I don't use it. It's just that I think I remember reading about it. If I find any note saying something about it, I'll post it right here!

**Comment by hannesmannerheim** [comment]
ok, thanks
