### ISSUE TITLE
Problem getting route for plugins/Qvitter/locale/de.json - No match for path "plugins/Qvitter/locale/de.json"

### ISSUE THREAD

**Issue by MarcusMoeller** [hannesmannerheim/qvitter#230]
I have installed the plugin as described in the Readme, but it does not seem to load correctly. I got an error like:

Problem getting route for plugins/Qvitter/locale/de.json - No match for path "plugins/Qvitter/locale/de.json"

The files are in the correct place and the config has been made as suggested. Do I have to restart queuemanager or something else to make it work?

**Comment by hannesmannerheim** [comment]
url to the instance?

**Comment by MarcusMoeller** [comment]
https://gnusocial.ch but I have it de-activated as it does not work. Should I activate it again for you to check?

**Comment by hannesmannerheim** [comment]
yes, please do!

**Comment by MarcusMoeller** [comment]
Done, there is not much to see, though as it seems to fail to load.

**Comment by hannesmannerheim** [comment]
thanks, you can deactivate it now

**Comment by hannesmannerheim** [comment]
hm, i wonder what the problem is. if you type https://gnusocial.ch/local/plugins/Qvitter/locale/de.json into your browser it should find the .json file, but it doesn't...

**Comment by hannesmannerheim** [comment]
my first thought was that it might be looking for the language file in /plugins/Qvitter instead of /local/plugins/Qvitter, but since that was not the case, i don't know. 

either the files doesn't exist, or there's some weird server setting regarding .json files, or there a problem in the .htaccess, or in lib/router.php... but qvitter is tested and working with the latest gnusocial nightly.

**Comment by hannesmannerheim** [comment]
now suddenly https://gnusocial.ch/local/plugins/Qvitter/locale/de.json is working!

**Comment by MarcusMoeller** [comment]
Yes, I had to add a mimetype to the nginx configuration (included defaults now for this site). Now I got an error:

Failed to get request GET /api/qvitter/allfollowing/marcus.json?

It is looking for /srv/gnusocial/api/qvitter/allfollowing/marcus.json which does not exist.

**Comment by hannesmannerheim** [comment]
still some server setting with json files i think

https://gnusocial.ch/api/statuses/public_timeline.xml works
https://gnusocial.ch/api/statuses/public_timeline.json doesn't work

**Comment by MarcusMoeller** [comment]
For me the first one does not work either.

Do I perhaps have to configure a value for:

$config['site']['qvitter']['urlshortenerapiurl'] = 'http://qttr.at/yourls-api.php';

I am not sure what would be the correct value here. There is no yourls-api.php script available in my nightly checkout.

**Comment by hannesmannerheim** [comment]
that's nothing to do with it.

the api files doesn't exist anywhere since they are created dynamically. maybe nginx needs to be set to send .json files through php somehow. i've never used nginx so i don't know how that works

**Comment by MarcusMoeller** [comment]
hmm. Do I still have to replace apiauthaction.php on nightly?

**Comment by hannesmannerheim** [comment]
nope

btw this is a problem even if you're not running qvitter, if someone wants to use a client for gnusocial.ch that uses the json-api

**Comment by hannesmannerheim** [comment]
compare e.g. https://gnusocial.ch/local/plugins/Qvitter/locale/idontexist.json with https://gnusocial.no/local/plugins/Qvitter/locale/idontexist.json

i don't think json files are sent to index.php for gnusocial's internal routing. 

maybe this rule in .htaccess doesn't match json files, for some reason:
RewriteRule (.*) index.php?p=$1 [L,QSA]

**Comment by hannesmannerheim** [comment]
but i'm just guessing...

**Comment by hannesmannerheim** [comment]
they apparently have nginx working on micro.fragdev.com:
http://fragdev.com/blog/gnusocial-on-nginx-with-php-fpm

the "Perform URL rewriting if a file doesn't exist" part sounds interesting

**Comment by hannesmannerheim** [comment]
ohhh, my memory should be better, but @knuthollund has solves exactly this before: https://quitter.se/notice/3487990

**Comment by MarcusMoeller** [comment]
At least https://gnusocial.ch/api/statuses/public_timeline.json works for now.

Now I see errors like this in the log:

2015-07-10 11:43:15 LOG_ERR: [gnusocial.ch:14413.e2552777 GET /api/statuses/public_timeline.json?t=1436528575732] ServerErrorAction: 400 [QvitterNotification] DB_DataObject error []: DB Error: no such table
#0 /srv/gnusocial/extlib/DB/DataObject.php(2656): Memcached_DataObject->raiseError(Object(DB_Error))
#1 /srv/gnusocial/classes/Memcached_DataObject.php(637): DB_DataObject->_query('SELECT  ntype ,...')
#2 /srv/gnusocial/extlib/DB/DataObject.php(451): Memcached_DataObject->_query('SELECT  ntype ,...')
#3 /srv/gnusocial/classes/GS_DataObject.php(134): DB_DataObject->find(false)
#4 /srv/gnusocial/local/plugins/Qvitter/QvitterPlugin.php(911): GS_DataObject->find()
#5 [internal function]: QvitterPlugin->onEndSetApiUser(Object(User))
#6 /srv/gnusocial/lib/event.php(105): call_user_func_array(Array, Array)
#7 /srv/gnusocial/lib/apiauthaction.php(97): Event::handle('EndSetApiUser', Array)
#8 /srv/gnusocial/actions/apitimelinepublic.php(159): ApiAuthAction->prepare(Array)
#9 /srv/gnusocial/lib/action.php(122): ApiTimelinePublicAction->prepare(Array)
#10 /srv/gnusocial/lib/action.php(101): Action->execute(Array)
#11 [internal function]: Action::run(Array)
#12 /srv/gnusocial/index.php(316): call_user_func('ApiTimelinePubl...', Array)
#13 /srv/gnusocial/index.php(330): main()
#14 {main}

**Comment by hannesmannerheim** [comment]
maybe you've disabled "schemacheck" in your config? you have to run that so that qvitter's tables are created

**Comment by MarcusMoeller** [comment]
Yeah, after running  php ./scripts/checkschema.php it finally works. Thanks a lot!

**Comment by hannesmannerheim** [comment]
:))
