### ISSUE TITLE
Keyboard navigation gets lost over Queet with image

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#233]
Steps to reproduce:
1. Log into Quitter.no: <https://quitter.no>
2. Go to my profile page: <https://quitter.no/ciencisto>
3. Scroll down with the J key until you pass over the Queet with an image of a hare: <https://quitter.no/notice/529589>

After it focuses on the Queet of a hare, the navigation gets "lost" two times before focusing on the next Queet.

Setup: Quitter.no in Firefox 38.0.5 on Fedora 22

**Comment by hannesmannerheim** [comment]
thank you!

**Comment by maliktunga** [comment]
It's really… solved? Already?! Wow, I thought it would take weeks to resolve. Tack så jättemycket!

**Comment by hannesmannerheim** [comment]
it was a very well described issue and easy to fix :)

**Comment by maliktunga** [comment]
Good, I hope to describe more issues as such in the future! ;o)
