### ISSUE TITLE
can't get url shortener to work [in Abrowser]

### ISSUE THREAD

**Issue by MarcusMoeller** [hannesmannerheim/qvitter#234]
I am trying to get the url shortener to work. I have first just set:

$config['site']['qvitter']['urlshortenerapiurl'] = 'http://qttr.at/yourls-api.php';
$config['site']['qvitter']['urlshortenersignature'] = 'b6afeec983';

in the config which did not help. Then I followed the instructions in shortener.php which lead to the same result.

**Comment by hannesmannerheim** [comment]
http://qttr.at/yourls-api.php doesn't work with most browsers if you're on https

shortener.php works on gnusocial.ch when i tried it:
https://gnusocial.ch/local/plugins/Qvitter/shortener.php?format=jsonp&action=shorturl&signature=b6afeec983&url=https%3A%2F%2Fgnusocial.ch%2F

try adding https://gnusocial.ch/local/plugins/Qvitter/shortener.php as the urlshortenerapiurl

**Comment by MarcusMoeller** [comment]
I have added that to the config. When I now click on the >url< button the wheel in the top bar starts spinning but nothing happens. Nothing special in the logs also.

**Comment by hannesmannerheim** [comment]
can i get a test account on gnusocial.ch?

**Comment by hannesmannerheim** [comment]
thanks. the shortener works for me.
what browser are you using?
what's the url you're trying to shorten?

**Comment by MarcusMoeller** [comment]
I am using Abrowser (FF) on Trisquel 7. If the shortener works, does it work inline or is the URL shortened when the dent is sent out?

**Comment by hannesmannerheim** [comment]
it works inline, the urls present in the queets should be shortened and replaced

**Comment by MarcusMoeller** [comment]
Here is an example I tried to shorten: http://www.linux-community.de/Internal/Nachrichten/VirtualBox-5.0-veroeffentlicht

**Comment by hannesmannerheim** [comment]
the url is shortened for me 
<img width="298" alt="skarmavbild 2015-07-10 kl 21 24 09" src="https://cloud.githubusercontent.com/assets/2437812/8627252/0fa98442-274a-11e5-9aff-e1007565eb2b.png">
<img width="301" alt="skarmavbild 2015-07-10 kl 21 24 17" src="https://cloud.githubusercontent.com/assets/2437812/8627259/12174fa2-274a-11e5-95dc-5de122bcb61f.png">

so maybe it's the browser..

**Comment by MarcusMoeller** [comment]
It was related to the RefControl Addon I am using. Thanks for verifying.

**Comment by hannesmannerheim** [comment]
ah great! i added some error reporting when shortening, so it was good this came up anyway.

**Comment by qirtaiba** [comment]
Can you please point me towards the error reporting code? I have the same problem and I'm not using a RefControl addon.
