### ISSUE TITLE
"apple.com" does not become a clickable link

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#236]
Event though "apple.com" and "ido.li" become blue in the message composer, the final Queet does not make them into clickable links.

**Comment by hannesmannerheim** [comment]
looks like this feature has been removed from gnu social...

**Comment by hannesmannerheim** [comment]
what do you think, should i try to re-implement the highlighting of links without protocol (http/https), or should i remove the highlighting of such links from the queet composer?

**Comment by maliktunga** [comment]
I'll try to answer that in an objective way: I tried writing "apple.com" on Twitter, Facebook and Google+. In all three cases, "apple.com" turned into a blue, clickable link. To make Quitter more intuitive, I would expect the same behavior.

**Comment by hannesmannerheim** [comment]
yes, i agree. although twitter doesn't make "quitter.se" into a link though. i wonder how they decided which top lever domains to highlight and which not to.

**Comment by hannesmannerheim** [comment]
i'll see if i can find the commit in gnusocial where it was removed. maybe i can just copy some code from that into qvitter.

**Comment by hannesmannerheim** [comment]
ah! it had become a setting: 
$config['linkify']['bare_domains'] = true;

**Comment by maliktunga** [comment]
So, is that on a server-level configuration?

**Comment by hannesmannerheim** [comment]
yes, but i've made that the default behaviour in qvitter now.

**Comment by maliktunga** [comment]
Thank you! By "default", does that mean that Quitter.no will enable it too?

**Comment by hannesmannerheim** [comment]
yes

**Comment by maliktunga** [comment]
Good :)
