### ISSUE TITLE
Blue link overlay becomes offset after three lines

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#237]
When I copy the following lines (altogether) in the pop-up message composer (the one which appears with the N key), the blue overlay that indicate their link nature becomes offset and even superposed.

> apple.com twitter.com
> google.com
> facebook.com
> wikipedia.org

Setup: Quitter.no in Firefox 38.0.5 on Fedora 22.

**Comment by maliktunga** [comment]
I noticed that the way in which I select the above lines can also affect the result. Try selecting the lines by left click-and-drag  without selecting the "a" of apple.com.

**Comment by maliktunga** [comment]
Alternative test:

1. Log into Quitter.no
2. Type the N key
3. Type "facebook.com" in the box
4. Press Enter
5. Type "google.com" in the box

As a result, the blue overlay of "google.com" should be offset by one line:

![screenshot from 2015-07-11 15-06-57](https://cloud.githubusercontent.com/assets/6393838/8634998/83f7be2e-27de-11e5-82a9-dbe3821cbd91.png)

**Comment by hannesmannerheim** [comment]
fixed, thank you!

**Comment by maliktunga** [comment]
Awesome, thanks to you! :grinning:
