### ISSUE TITLE
Top bar buttons have no mouseover text

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#245]
I am referring to the profile image button and the pencil button.

Here is how it looks like on Twitter:
![screenshot from 2015-07-21 17-42-06](https://cloud.githubusercontent.com/assets/6393838/8813244/e234c7d6-2fcf-11e5-8ad0-8ae60e5b53f1.png)

As you can see, a mouseover on the profile image displays "Profile and settings" while the pencil button already displays the text "Tweet".

**Comment by hannesmannerheim** [comment]
also implemented in https://github.com/hannesmannerheim/qvitter/commit/89b82becf40c4c53b714cec311f4487b412c121a
