### ISSUE TITLE
Inconsistency between serif and sans-serif

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#247]
Let us use the following screenshot as a reference:

![screenshot from 2015-07-21 17-54-40](https://cloud.githubusercontent.com/assets/6393838/8813459/af6a247a-2fd1-11e5-9d89-10ec35a7e8c4.png)

Notice that text in the side banner is in serif, while the same text in the profile banner is in sans-serif. "Compose a new notice…" on the left is in serif, but clicking in the box and typing in it results in sans-serif text. The stream of messages are all in sans-serif, but the "Notices / Mentions / Favorites" are in serif.

That is what I consider as inconsistency.

I checked Diaspora, Facebook, Twitter and Google+.
Conclusion: serif is nowhere to be found.

Sans-serif has become kind of a standard for the Web because of its cleaner and more legible appearance on computer displays. Nowadays, we're seeing a resurgence of serif particularly in eBook readers, but that is mainly because of the new Retina displays and of serif's "book appeal". For most of us, and particularly on a modern-looking social network, sans-serif is way preferable.

**Comment by hannesmannerheim** [comment]
it is sans-serif everywhere in my browser... let's see if i can fix this in the blind

**Comment by hannesmannerheim** [comment]
@maliktunga can you check if this is fixed on quitter.se now?

**Comment by maliktunga** [comment]
@hannesmannerheim The issue is fixed. Thank you very much! It looks much better now.
