### ISSUE TITLE
Set a (lower) limit of sidebar breadcrumbs

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#249]
I am referring to the history links that add up below the box with Timeline, Notifications, Mentions, Favorites, Public Timeline and The Whole Known Network. I will not share screenshots due to privacy.

After some searches and profile visits, there are now more than 50 breadcrumbs in my sidebar. That is a nice little feature, but 50 is excessive.

As a reference, Mozilla Firefox' pull-down/right-click history seems to display a maximum of 15 entries, including the current page.

**Comment by hannesmannerheim** [comment]
good suggestion. i'm thinking of making a way to pin favorites in the top of the list.

**Comment by hannesmannerheim** [comment]
implemented in https://github.com/hannesmannerheim/qvitter/commit/89b82becf40c4c53b714cec311f4487b412c121a
