### ISSUE TITLE
Bio, Location and Homepage cannot be emptied

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#251]
Quitter.no on Firefox 39.0 (Fedora 22)

Steps:
1. Go on Quitter.no
2. Go to your profile page
3. Click on "Edit profile"
4. Empty the Bio/Location/Homepage
5. Click on "Save changes"

Result: the previous input for the Bio/Location/Homepage comes back.
Expected: the boxes become empty.

**Comment by hannesmannerheim** [comment]
i think it's best to fix this at the gnu social level, i have submitted a merge request https://git.gnu.io/gnu/gnu-social/merge_requests/28
