### ISSUE TITLE
Post is empty - although it isn't

### ISSUE THREAD

**Issue by annando** [hannesmannerheim/qvitter#252]
Please compare 

* https://status.pirati.ca/conversation/1389953
* https://pirati.cc/conversation/128733
* https://pirati.ca/display/stat24459855b36293a92c5116119185

with this one:
https://quitter.se/notice/3898631

The second post is empty. Question is if this is a Qvitter issue, since the post appeared correctly on other servers.

**Comment by maliktunga** [comment]
@annando Is that the same post?
https://quitter.no/notice/561300

**Comment by annando** [comment]
Yeah, it is.

**Comment by maliktunga** [comment]
@annando Thus, this means that it is not a Qvitter issue. The only difference I know between Quitter.se and Quitter.no is the character limit: Quitter.se allows up to 140 characters per message while Quitter.no allows up to 1000 characters per message.

**Comment by annando** [comment]
It could be a qvitter issue related to the character limit.

**Comment by maliktunga** [comment]
@annando Indeed, it could!

**Comment by hannesmannerheim** [comment]
character limit is at gnu social level. 
i've only seen this happen at instances running older versions of gnu social (like quitter.se), so i strongly suspect it is something that is already fixed in newer gnu social.
closing because not a qvitter issue.
