### ISSUE TITLE
Group says that there is "0" admins when there is 1

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#254]
The group: https://quitter.no/group/mondlangisteyo/admins

What I see: 
![screenshot from 2015-07-26 21-58-59](https://cloud.githubusercontent.com/assets/6393838/8897342/935de33e-33e1-11e5-94e4-918cc4756baf.png)

Set-up: Quitter.no in Firefox 39.0, Fedora 22

**Comment by hannesmannerheim** [comment]
add as gnu social issue https://git.gnu.io/gnu/gnu-social/issues

qvitter gets this number from gnu social backend. quitter.no's api is reporting 0 admins for that group
