### ISSUE TITLE
Support for "fancy urls" is broken

### ISSUE THREAD

**Issue by sistemascta** [hannesmannerheim/qvitter#256]
I have configured support for fancy urls in vanilla gnu-social and works OK, but qvitter seems to ignore the settings in .htaccess and config.php, all queets + links on sidebar (notifications, mentions, favorites, etc) points to foobar.com/index.php/[user], and clicking on them leads you to foobar.com/ on  a new window.

Running GNU-Social 1.2.x + Qvitter 5-alpha on debian wheezy.

**Comment by hannesmannerheim** [comment]
qvitter gets the "index.php" part from gnusocial, so it means fancy urls are not configured properly. this happens for me if i don't rename htaccess-sample to .htaccess before running install.php.

anyway, i don't think this is a qvitter issue. configuring fancy urls in gnusocial is tricky, and i when i have had troubles, i have just re-installed everything to get it working properly.

closing this, as i think it should be an issue in the gnu social git instead.
