### ISSUE TITLE
Mentions do not work on in-line reply [windows]

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#259]
1. Log into Quitter.no
2. Go to [this page](https://quitter.no/notice/599415)
3. Click on the message if it is not yet expanded
4. Click in the reply box if it is not yet activated
5. Right next to "@moozi ", type "!p"

What is expected: the "!p" becomes blue
What happens: the "!p" stays black

I noticed that erasing the space just after "@moozi" then inserting another space solves the problem.

**Comment by hannesmannerheim** [comment]
which browser? i can't reproduce in firefox or webkit

**Comment by maliktunga** [comment]
Oh sorry. Microsoft Edge 20 on Microsoft Windows 10.

**Comment by hannesmannerheim** [comment]
oh, ok, i'll probably not be able to fix it then

**Comment by maliktunga** [comment]
By any chance, is the automatically inserted space _not_ the same as a normal space?

**Comment by maliktunga** [comment]
Changed the title due to the fact that @mentions do not function either.

**Comment by hannesmannerheim** [comment]
yes, a html-space is inserted, &nbsp;

**Comment by hannesmannerheim** [comment]
i just tried something in the blind, do you have an account on quitter.se that you can try with, and see if it's fixed?

**Comment by maliktunga** [comment]
It functions on quitter.se now!

**Comment by hannesmannerheim** [comment]
good! thx

**Comment by maliktunga** [comment]
Thanks to you!

**Comment by maliktunga** [comment]
Somehow it does not seem fixed as I expected. On Quitter.no and Quitter.se, the mention _does_ become blue in the text composer, but once the message is sent, the mention turns back into plain unlinked text.

**Comment by hannesmannerheim** [comment]
it can happen if you're not a member of the group

**Comment by hannesmannerheim** [comment]
it will also be black while posting, but turn blue when the server responds and it is saved

**Comment by maliktunga** [comment]
Sorry, I should clarify that this issue also applies to hashtags and @mentions

**Comment by hannesmannerheim** [comment]
but you mean that they are black while it says "posting..."? and then get highlighted?

**Comment by maliktunga** [comment]
No, sorry, I meant that it became black while posting but then stays black once posted.

**Comment by hannesmannerheim** [comment]
give me a permalink to such a notice

**Comment by maliktunga** [comment]
There: https://quitter.se/notice/3969497

**Comment by hannesmannerheim** [comment]
can't reproduce it in firefox. you are testing with that microsoft browser, right?

**Comment by maliktunga** [comment]
That Microsoft browser, yes :)
