### ISSUE TITLE
Dark rectangle overlay when uploading an image

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#260]
1. Go on Quitter.no
2. Click on the blue pencil button in the top right corner
3. Click the picture button and upload an image

What is expected: nothing
What happens: while the image is being uploaded, a dark rectangle overlays the message entry box and vertically stretches the page.

The bug can be reproduced on the latest Firefox (Fedora 22) and on Microsoft Edge 20 (Windows 10)

**Comment by maliktunga** [comment]
Was quitter.se updated to fix that? I can still see the dark rectangle on Microsoft Edge 20.

**Comment by hannesmannerheim** [comment]
nope, quitter.se not updated yet
