### ISSUE TITLE
Classic interface access without logging in

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#264]
There's no way to see the website from the classic interface because there's no button for this in the toolbar. It could be cool to add one, maybe near to the language menu :) 

![captura de pantalla_2015-08-21_12-14-28](https://cloud.githubusercontent.com/assets/7888062/9406195/92a8e3e0-47fe-11e5-8acd-31a4d2a91a00.png)

**Edit**  
Even better: a menu with an access to: 
- Classic interface
- FAQ
- Language

**Comment by hannesmannerheim** [comment]
this is a concious choice, i don't want to confuse new users with the existance of two different user interfaces. the front logged-out page should, imo, be very clean and send a very clear message. so i'm closing this.

**Comment by moshpirit** [comment]
Oh, OK and what about the FAQ?

**Comment by hannesmannerheim** [comment]
i want a simpler/different faq for logged out users in that case. the current faq is written for the logged in user.

**Comment by moshpirit** [comment]
Perfect, maybe it could be better an introduction to GNU social itself

**Comment by moshpirit** [comment]
# FAQ 

**This is a _basic_ guide to help you understand how GNU social and** /server name/ **works**.  
When you get started a more complete and helpful FAQ will be shown. If you still have any doubt, just write it with the tag "#Help". This is a really helpful community so it shouldn't last much time to get answered.

This guide to Quitter is for new users in particular. It concentrates on how to get along, without going too much into details. For specific technical questions (e.g., how to set up a GNU social-instance) please ask in the groups !gnusocial and !sn, or on Quitter's Public Timeline. You may also find technical information at http://federation.skilledtests.com/

The sequence of points follows roughly the frequency of the questions that have been asked by new users.

Other GNU social FAQs & wikis:

- https://wiki.loadaverage.org/gnusocial/begin_to_be_social
- http://wiki.gnusocial.de (in German)

### What is Quitter? 

Quitter is one of many GNU social instances with a familiar user interface.

The original GNU social web user interface is available as "Classic Quitter", selectable from your header avatar (upper right).

----
**Note**: also add the new option for no signed up users.

----
### What is GNU social/StatusNet and the Federation? 

GNU social is the evolution of a decentralised microblogging platform called StatusNet, but it won't be mentioned again. 

Being GNU social a decentralised microblogging platform means that there's no need to use one centralised server that controls all the data so no one can control the entire microbloging service which is really helpful to fight censorship.

There is no central "unit" the breakdown of which could bring down the whole network. If one instance goes down or the admins start doing things you don't like, you can create your account on another instance. You will still be on the GNU social-network and still be able to communicate with your GNU social-friends. You just need to tell your contacts your new address.

Users of one instance (or service) can follow, be followed by, and communicate with users of any other instance.

The current number of microblogging instances using the GNU social software is probably about 50, Quitter is one of them (other instances are, e.g., loadaverage.org, status.vinilox.eu, micro.fragdev.com, gnusocial.de, indy.im, quitter.no, rainbowdash.net, etc.). As they all use the same software (GNU social) and transmission protocol (OStatus), they can talk to each other just like e-mail servers can talk to each other, even though they are independent and run by different companies.

Connections between instances are established by users following each other. Via such followings all these instances can (at least in principle) be joined into one compound structure or network of self-contained instances. This is called the Federation. GNU social is structured in such a way that there needs to be only one following of a user a from instance A to a user b from instance to B to make b visible to everybody in instance A via The Whole Known Network which is the wider network of instances as seen by Quitter. It looks different on, say, loadaverage, because on loadaverage there are different followings to remote instances than on Quitter.

Addresses on GNU social look like this:

@user@instance.org

If you follow another user, or if the user is on the same instance, you may omit the ...@instance.org part and just use the short address

@user

### Apps

The network's name is "GNU social", so what you want is a GNU social app. (Remember, Quitter is just one instance of the GNU social- or StatusNet-federation.) so you won't find any "Quitter app" in Google Play Store or Apple's AppStore.

You can find information on clients and links to downloads in the complete FAQ and here:

- http://federation.skilledtests.com/Statusnet_clients.html
- http://wiki.gnusocial.de/gnusocial:clients (in German)

### New Quitter and Classic Quitter

New Quitter uses the default user interface. It is visually very similiar to other well known commercial microblogging services. Its technical name is "Qvitter" (aka "New Quitter", the technical difference is shortly explained in the complete FAQ).

Classic Quitter is the canonical GNU social interface. At the moment some settings and features (e.g., creating a group) have to be done in Classic Quitter as they are not yet fully implemented in New Quitter.

To switch to Classic Quitter go to

    Your header avatar (upper right) → Classic Quitter

### What are those three Timelines on New Quitter? 

There are three timelines that show differerent notices (depending on the sources):

- Timeline ("Home"):
all notices from the people you follow (not just the ones they send to people you happen to follow as well).

- Public Timeline:
all notices posted by Quitter accounts.

- The Whole Known Network:
not only all notices of the Public Timeline but also those of all people on other ("remote") instances of the GNU social-/StatusNet-federation followed by at least one Quitter user (i.e., accounts known to Quitter, see above What is the Federation?).

### Follower requests 

In general, you will want to stick with the default settings "let anyone follow me", but you can also select "Make updates visible only to my followers" and "Ask me first". With this last option you will receive e-mail notifications when someone wants to follow you. It leaves the subscription request pending until you either confirm or reject it. 

### Can I delete my Quitter account?

Yes, you can delete your account, and all your notices will be deleted on Quitter as well – this will break conversation threads. If you restore your account on another instance, it's better to rename your Quitter account to something like MyNickhasmovedtoFragdev instead of deleting it.

### Groups
#### Public Groups

On Quitter you can create a group for nearly any topic, like Feminism, Football, FreeBSD. ("Nearly" because the laws in the country hosting the website may prohibit such things as slander and hate speech.)

You can be a member of as many groups as you like. As group-member you can post to the whole group by attaching ! to the group name, e.g., !feminism, in the notice. All group members, whether or not they follow you, will get the notice in their Home Timelines. You follow and unfollow a group like you follow and unfollow a person.

#### Private Groups

An admin of a group has the option to declare it private. This means:

1. New members must be approved by the admin(s)
2. All notices are forced to be private.
That is, notices in the group are only visible to group members.

### Follow someone on a remote instance

In New Quitter, when you click a remote nickname in New Quitter you are brought to a small profile window showing the full remote address, e.g., @blabla@status.vinilox.eu. Click the button "Follow". That should be all.

You can also do it in Classic Quitter and manually (explained in the complete version of the FAQ)

### Follow keywords and hashtags

Similar to following persons or groups you can subscribe to (or follow) hashtags and search words. Notices containing them will then appear in your Home timeline.

Following search words and hashtags is not limited to notices from accounts on Quitter but covers notices from remote instances as well.

---- 
**Notes**: 
- This is an example for Quitter so it should be modified to automatically introduce the instance name.
- I've deleted "StatusNet" since it's a simple and basic guide and it can be a bit confusing discovering all of these weird words: GNU social, Status Net, Quitter, Qvitter/New Quitter, Ostatus, etc 
- I've changed the format to be more visual here in GitHub.

Thoughts? I've tried to make it as simple and brief as possible and focus on explaining what's GNU social, how it works and its main features.

**Comment by hannesmannerheim** [comment]
cool! but i think we should leave the "Follow keywords and hashtags" and "Follower requests" out, since neither feature works in qvitter

**Comment by moshpirit** [comment]
As you prefer but following keywords and hagstags is a great feature. Anyway, it's still on the main FAQ :)
