### ISSUE TITLE
youtu.be URLs and shortened YouTube URLs do not display video in message

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#270]
youtu.be, not shortened: https://quitter.se/notice/4010162
youtu.be, shortened: https://quitter.se/notice/4010164
YouTube, not shortened: https://quitter.se/notice/4010167
YouTube: shortened: https://quitter.se/notice/4010168

As you can see, only the non-shortened YouTube URL causes the video to be displayed below the message.

**Comment by hannesmannerheim** [comment]
if this still doesn't work on quitter.se (when i update qvitter there), it's due to non-qvitter specific gnu social setup. so closing this.
