### ISSUE TITLE
Wrong formed HTML tags

### ISSUE THREAD

**Issue by voylinux** [hannesmannerheim/qvitter#277]
Today I have seen a mistake in the Qvitter theme. Inspectic the code in the browser, I see it is because of wrong format in HTML tags.
I attach a screenshot.
![gnusocial_bug](https://cloud.githubusercontent.com/assets/1538304/10123676/6998152a-6540-11e5-8f93-d5c1d1a2396c.png)

**Comment by hannesmannerheim** [comment]
thanks! i've seen that too! but i *think* it is fixed already in https://github.com/hannesmannerheim/qvitter/commit/90091331993e16a168e3b07b424961167c82cd95

**Comment by voylinux** [comment]
Nice!
