### ISSUE TITLE
Profile image popup appears behind profile overview card

### ISSUE THREAD

**Issue by maliktunga** [hannesmannerheim/qvitter#278]
1. Go on Quitter.no.
2. Hover a profile image. The profile overview card appears.
3. Click on the profile image in the profile overview.

Expected: The profile image pops up on top of the page.
What happens: The profile image pops up, but behind the profile overview card.

I use Mozilla Firefox 41.0.1 on Microsoft Windows 10.

**Comment by fxdwg** [comment]
FYI: quitter.no updated with latest fixes
