### ISSUE TITLE
Notifications error message

### ISSUE THREAD

**Issue by blog2read** [hannesmannerheim/qvitter#282]
Hi
With recent **qvitter** I have a "1" in the menu left under notifications. When clicking on that number get a error message - something seems to be missing..

Any idea?
![qvitter03](https://cloud.githubusercontent.com/assets/6249323/10278781/6b085804-6b60-11e5-80b5-d012f3832954.png)

**Comment by hannesmannerheim** [comment]
have you disabled checkschema and forgot to run it manually after installing qvitter?

**Comment by blog2read** [comment]
Yes I forgot it. Bun now I just ran  "checkschema" again - but I get the same error message.

**Comment by hannesmannerheim** [comment]
can you screanshot the "1" thing?

**Comment by blog2read** [comment]
Here we go.
![qvitter04](https://cloud.githubusercontent.com/assets/6249323/10279388/9db66f5c-6b65-11e5-8352-08fcaee593ec.png)

**Comment by hannesmannerheim** [comment]
ah, now i understand :) you have one unread notification. but the error still persists? if so, check 
1) do you have a 'qvitternotification' table in your db
2) check the gnu social log file and look for the 404 error and see if it gives us more to go on

**Comment by blog2read** [comment]
1) DB ok
2) Must be this problem:

    2015-10-05 11:59:15 LOG_ERR: [social.bitcast.info:27523.e0e9dbcd GET /api/qvitter/statuses/notifications.json?t=1444046354338] ServerErrorAction: 404 There is no profile with id==113

**Comment by hannesmannerheim** [comment]
that's strange. if you empty the qvitternotification table, do you still get the error?

**Comment by blog2read** [comment]
I found the entry in qvitter table from "id=113" and deleted it - and the error message has gone :)

**Comment by hannesmannerheim** [comment]
ok. good. but i don't understand why that exception were thrown, qvitter does checks to prevent exactly that from happening, and should have just skipped the invalid entry. tell me if it happens again!

**Comment by blog2read** [comment]
Ok will do. BTW I "upgraded" qvitter a little bit for my #gs :-) Just added new fonts and I am using now "Roboto" instead of "Arial" - https://social.bitcast.info

**Comment by hannesmannerheim** [comment]
cool :) (but qvitter uses helvetica neue primarily)

if you want to speed up page load you can make your webserver set a long expiry date for .css and .js files

**Comment by blog2read** [comment]
Thanks for the tip - activated mod_expires now. But we are quit OT now :)
