### ISSUE TITLE
QvitterEndShowHeadElements vs EndShowHeadElements

### ISSUE THREAD

**Issue by singpolyma** [hannesmannerheim/qvitter#297]
Why does Qvitter have its own hook for this?  Wouldn't it make more sense to use the standard event so it will work with more existing plugins?

**Comment by hannesmannerheim** [comment]
that might add css that is specific for the standard ui, which might break qvitters css

**Comment by hannesmannerheim** [comment]
also: it would not work as expected in plugins, since i've seen that some plugins check which action is calling the event, and in qvitter's case that is _qvitter_ not _showstream_ for example

**Comment by singpolyma** [comment]
Hmm, re the specific instanceof checks, that's a good point
