### ISSUE TITLE
Show how long have been a note reshared

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#300]
Is there any way to show how much time passed since an user shared a note?

Maybe some "Repeated by username X minutes ago" would looks better. 
This is how it looks now: ![instantanea17](https://cloud.githubusercontent.com/assets/7888062/10872222/55852c5c-80fd-11e5-97bc-90a27e6316c5.png)

Maybe the GS code doesn't allow this option but I don't know, if so, please let me know in order to report it.

**Comment by hannesmannerheim** [comment]
added a tooltip with the time when hovering the green requeet icon
