### ISSUE TITLE
Add option to specify under what language the following post will be

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#310]
So that one can filter the languages that one knows to avoid the languages that one doesn't know.

**Comment by hannesmannerheim** [comment]
how would we treat posts that the author didn't select a language for?

**Comment by pizzamaker** [comment]
There should be a fallback language selected in Preferences. As in 'Declare all my posts as English unless stated otherwise'.

**Comment by hannesmannerheim** [comment]
i don't think a lot of users will bother with that setting. if half of the users don't select the correct language for their notices the whole thing will be useless. i don't believe there's a good solution for this.
