### ISSUE TITLE
TypeError: streamObject is undefined

### ISSUE THREAD

**Issue by hanappe** [hannesmannerheim/qvitter#312]
TypeError: streamObject is undefined stream-router.js:456:0

It seems that function pathToStreamRouter(path) does not return a valid streamObject. 
The last block at the end of the function "if(window.pluginStreamObjects.length > 0)" returns streamObject if length>0 but nothing is returned when length==0. 

Quick fix:
        // other plugins can add streams to Qvitter
        if(window.pluginStreamObjects.length > 0) {
            // ...
        }
       // ADDED: return the streamObject
       return streamObject;
    }

**Comment by hannesmannerheim** [comment]
how do i reproduce the bug?

**Comment by hannesmannerheim** [comment]
i added return false instead, does that solve your problem?

**Comment by hanappe** [comment]
I did a clean install as follows:

- cd /var/ww && git clone https://git.gnu.io/gnu/gnu-social.git --branch 
nightly --single-branch
- create db + db user
- mkdir avatars background file
- cp htaccess.sample .htaccess; change RewriteBase
- chown -R www-data.www-data /var/www/gnu-social
- open https://myserver/gnu-social/install.php
- cd /var/www/gnu-social; mkdir local/plugins; cd local/plugins; git 
clone https://github.com/hannesmannerheim/qvitter; mv qvitter Qvitter
- edit config.php, copy/paste from 
https://github.com/hannesmannerheim/qvitter/blob/master/README.md

Note that the GNU Social url contains a directory 
(https://myserver/gnu-social/...). There seem to be other issues related 
to that.

**Comment by hannesmannerheim** [comment]
ok so you mean nothing works? it's not when you do something specific?

**Comment by hannesmannerheim** [comment]
ah, now i see: "Note that the GNU Social url contains a directory"

qvitter does not support that. i thought i had written it in the readme

**Comment by hannesmannerheim** [comment]
#14

**Comment by hannesmannerheim** [comment]
sorry for my bad documentation, i have added the info in the readme now.

**Comment by hanappe** [comment]
Thanks! I'll move the installation.
