### ISSUE TITLE
Feature: Images previews without opening the "queet"

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#32]
Just like Twitter does:
Now, if we want to see the picture, we have to open the queet in the TL, what I'm suggesting it's to show the picture by default without any need of clicking the queet.

**Comment by gordon-morehouse** [comment]
I want this. Quitter.se isn't the only Qvitter instance. Include a checkbox to turn it off if you must, IMO.

Currently I see that quitter.se drops an attachment URL into a tweet, which doesn't appear to work the way this feature request imagines (inline display) on Quitter.se OR on Twitter.
