### ISSUE TITLE
Add more keyboard shortcuts

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#320]
L - like a queet
R - requeet

and perhaps more?

**Comment by hannesmannerheim** [comment]
isn't f for fav and t for requeet working?

**Comment by pizzamaker** [comment]
Oh sorry! I wasn't aware of those. Are these written down somewhere?

**Comment by hannesmannerheim** [comment]
yes, there's a link in the menu in the top bar :)
