### ISSUE TITLE
sidebar notice text (logged out) not displayed

### ISSUE THREAD

**Issue by MarcusMoeller** [hannesmannerheim/qvitter#322]
I would like to define a sidebar text for everyone not logged in. I have defined it in the "Qvitter sidebar notice text (logged out)" section but it's not displayed. On our instance it is not possible to register directly (invite only) so that elements are not displayed on the page (not sure if that matters).

**Comment by MarcusMoeller** [comment]
Still not shown for logged out users.

**Comment by hannesmannerheim** [comment]
it is for me 
<img width="438" alt="skarmavbild 2015-12-13 kl 13 40 55" src="https://cloud.githubusercontent.com/assets/2437812/11767015/3452589e-a19f-11e5-9cab-8684e6442e78.png">

**Comment by MarcusMoeller** [comment]
Ok, I am going to check again.

**Comment by hannesmannerheim** [comment]
changed the default font color to white. i had only tried it with an image before

**Comment by hannesmannerheim** [comment]
@MarcusMoeller how did it go?

**Comment by MarcusMoeller** [comment]
Everything is fine, thanks
