### ISSUE TITLE
'Remote follow' fails 

### ISSUE THREAD

**Issue by jordila** [hannesmannerheim/qvitter#328]
Error Message says : 'INTERNAL SERVER ERROR no candidate paths for action 'posts' ' 

In laMatriz.org node.

When switching to 'Classic' GNU Social interface , problem disappears... thus making me thing about a potential Qvitter bug (?)

![gnu-social_remote-follow_internal-server-error](https://cloud.githubusercontent.com/assets/1966068/11886764/ab545742-a525-11e5-971c-6b54589ee8bd.png)

with love

**Comment by hannesmannerheim** [comment]
sorry about the delay with this issue, do you remember which user you tried to follow?

**Comment by hannesmannerheim** [comment]
i was just about to close this, but then i realised what the problem might be. it could be the Hedero plugin's "post" action that comes in conflict with some other post action in GNU social. the solution might be to change the name of hedero's post action to HederoPost or something like that.
