### ISSUE TITLE
Mark unread notification as read if you've just replied to the queet

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#331]
...as opposed to having to click on Notifications simply to mark all as viewed.

**Comment by hannesmannerheim** [comment]
this should already be the case. are you sure it's not already working?

**Comment by pizzamaker** [comment]
True, it's working. Is it possible to also implement this when you requeet or favorite a queet?

**Comment by hannesmannerheim** [comment]
also already implemented, although with a slight delay

**Comment by pizzamaker** [comment]
Cool, thanks.
