### ISSUE TITLE
Sometimes user's "queets" are not shown

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#336]
I don't know why :( sometimes, after a few refreshes the notes get charged, but not always work this way and no matter the number of the posts:

e.g. (4 queets)

![captura de pantalla_2016-01-02_21-38-07](https://cloud.githubusercontent.com/assets/7888062/12076021/8feff062-b199-11e5-9f2f-5c150aa5b09f.png)

**Comment by hannesmannerheim** [comment]
this can have different causes, but one is that gnu social's api reports incorrect amount of notices, because so called acitivty-notices are included in the count. the user might not have posted anything yet, but liked a couple of notices for example

**Comment by moshpirit** [comment]
I see, BTW, should be shown the total amount of queets? (Including "user has marked ___ as favourite" and "user has started following ___") that can be a bit confusing imo

**Comment by hannesmannerheim** [comment]
definitely. i'm trying to fix the gnusocial code right now

**Comment by hannesmannerheim** [comment]
submitted a merge request to the gnu social repo https://git.gnu.io/gnu/gnu-social/merge_requests/73

**Comment by moshpirit** [comment]
Great, man!! :D
