### ISSUE TITLE
Add a .onion address for quitter.se

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#341]
Probably not the best repo to do it, but this would be very useful for Tor users, particularly in repressive countries like China and Iran.

**Comment by moshpirit** [comment]
Maybe it would be better to be able to do it in any GNU social server so could you also report it [here](https://git.gnu.io/gnu/gnu-social/issues)?

**Comment by pizzamaker** [comment]
I imagine this is an issue for individual instances, but it may be worth trying on gnu social too

**Comment by hannesmannerheim** [comment]
i don't have any experience with tor, so i don't know how to do this. but i think it will need some changes to qvitter, so it can stay here as a feature request.

**Comment by pizzamaker** [comment]
I believe this is how to do it: https://www.torproject.org/docs/tor-hidden-service.html.en

**Comment by moshpirit** [comment]
[GNU social GitLab issue](https://git.gnu.io/gnu/gnu-social/issues/118). 

>very useful for Tor users, particularly in repressive countries like China and Iran.

Wouldn't be easier just using Tor Browser?

**Comment by hannesmannerheim** [comment]
@pizzamaker it's not a priority for me to read up on this right now. but if a qvitter site was available on a second domain, be it a .onion domain, qvitter will have to be modified with this in mind, since it builds a lot of its features upon the domain name in the location bar

**Comment by hannesmannerheim** [comment]
yes and i think @moshpirit is right. why not just use the tor browser? isn't .onion domain for hiding the _server_?

**Comment by mmn** [comment]
As I mentioned in the issue over at https://git.gnu.io/gnu/gnu-social/issues/118 there's nothing stopping anyone from running their separate

Packaging tor, configuring a hidden service and then running a webserver to make it all work together is not within the scope of GNU social - and I'd guess definitely not qvitter either. That task is up to a system administrator running the instance. The software itself is pretty DNS-backend-agnostic.

**Comment by hannesmannerheim** [comment]
thanks, closing this

**Comment by moshpirit** [comment]
Agree, thanks for the support
