### ISSUE TITLE
"User has marked ___ as favourite"

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#342]
I'm being notified twice about favourites: 

![captura de pantalla_2016-01-06_11-08-39](https://cloud.githubusercontent.com/assets/7888062/12140218/5d351754-b466-11e5-8ee1-2b6ba4ed7183.png)

**Comment by hannesmannerheim** [comment]
@mmn have you updated qvitter on .es?

**Comment by mmn** [comment]
Hannes Mannerheim <notifications@github.com> skrev: (6 januari 2016 11:20:53 CET)
>@mmn have you updated qvitter on .es?

No, I'll do it any minute now!


-- 
Mikael Nordfeldth
XMPP/mail: mmn@hethane.se

**Comment by moshpirit** [comment]
Fixed! thanks! :)
