### ISSUE TITLE
Add support for quoted tweets

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#344]
Similar to what was implemented with quoted notices. Would be a nice improvement, especially for these accounts I bridge from Twitter to GNU social.

**Comment by hannesmannerheim** [comment]
should already work if you paste the local url for the tweet (the link on the timestamp)

**Comment by pizzamaker** [comment]
It doesn't seem to be working. Is something wrong here?

https://quitter.no/notice/901431

https://quitter.se/notice/4401084

**Comment by hannesmannerheim** [comment]
you need to post the _local_ url the the tweet. but neither quitter.se or quitter.no have two-way twitter bridge, to there is no local versions of the tweets there. but _if_ you have an instance with two way twitter bridge, it will probably work if you find the local gnu social url to the tweet.

**Comment by vinzv** [comment]
Quoting notices seems not to work on mobile Safari. I can't test it myself but user https://quitter.se/rigsbysiv reported it to me.

**Comment by hannesmannerheim** [comment]
thanks. but i don't have any ios device to test with, so i will need much more details, screenshots etc
