### ISSUE TITLE
Favicon's background

### ISSUE THREAD

**Issue by postblue** [hannesmannerheim/qvitter#347]
The background of the favicon should be completely transparent, no?

![](http://i.imgur.com/IjjvXz2.png)

**Comment by hannesmannerheim** [comment]
we should switch to @moshpirit's gnu as favicon also!

**Comment by moshpirit** [comment]
Oh! What an honor!! :D thanks!!

**Comment by postblue** [comment]
@hannesmannerheim Indeed!
@moshpirit Your icon is awesome, it would be a shame to not use it.

**Comment by moshpirit** [comment]
:') thank you!!

**Comment by postblue** [comment]
@hannesmannerheim For some navigators, SVG favicons are possible. http://caniuse.com/#feat=link-icon-svg

**Comment by hannesmannerheim** [comment]
cool, i didn't know that. we can have .png as fallback

**Comment by moshpirit** [comment]
actually _my personal opinion_ is that the GS logo should stay and use my logo as the default new avatar. But still an honor. Maybe I could modify a little the current GS logo or something if you like
