### ISSUE TITLE
Home button and mark all as read

### ISSUE THREAD

**Issue by abjectio** [hannesmannerheim/qvitter#348]
Two suggestions for new features. Coming from notice : https://quitter.no/notice/911643
From: @victorhck@quitter.no

"just 2 suggestion for quitter: 

Wouldn't be useful to add a button at the bottom to go up to the page, when have scroll down a lot? 

Why not to add a buttom called "Mark all as readed" to check all the notifications just with one click?? 

Thnx... :)"

**Comment by hannesmannerheim** [comment]
both actually exist already :) 

click somewhere on the top bar to scroll to top.

"mark all as read" is in the cog menu in the stream header (but it is two clicks)

**Comment by abjectio** [comment]
True - thanks.
