### ISSUE TITLE
Qvitter is not thumbnailing webm videos

### ISSUE THREAD

**Issue by pizzamaker** [hannesmannerheim/qvitter#352]
Case in point: https://quitter.se/notice/4440286

**Comment by pizzamaker** [comment]
It works in the permalink, but not when I see it in a feed: https://quitter.se/nicolasmaia

**Comment by hannesmannerheim** [comment]
qvitter's issue tracker has moved here https://git.gnu.io/h2p/Qvitter

but this is a gnusocial issue: https://git.gnu.io/gnu/gnu-social

(in the permalink there is no thumbnail, it's the video that is partially loaded)

**Comment by hannesmannerheim** [comment]
apparently there is already a GS plugin called "VideoThumbnails", i tried it but it isn't working very well yet.

**Comment by pizzamaker** [comment]
For reference: this bug on GNU social https://git.gnu.io/gnu/gnu-social/issues/128
