### ISSUE TITLE
preview images not displayed

### ISSUE THREAD

**Issue by LiohMoeller** [hannesmannerheim/qvitter#354]
In the past, when someone posted an image, a preview has been displayed in the timeline. With recent updates, only the link to the image is displayed instead.

**Comment by hannesmannerheim** [comment]
thumbnail generation seems to be broken on your instance. the images displayed in the default gnusocial ui are actually the full size images. 
<img width="558" alt="skarmavbild 2016-03-27 kl 10 18 13" src="https://cloud.githubusercontent.com/assets/2437812/14064492/675357d0-f405-11e5-9ec3-6bbeb03dcc1e.png">

so this is a gnusocial issue. 

btw new qvitter issue tracker is at https://git.gnu.io/h2p/Qvitter/issues
