### ISSUE TITLE
Automatic username introduction doesn't show all the usernames

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#37]
If I write [@]v (without the square brackets) a list of names appears, but I only can see the first one:
![instantanea8](https://cloud.githubusercontent.com/assets/7888062/5603897/53a67158-939a-11e4-9077-262685049ac0.png)

**Comment by hannesmannerheim** [comment]
this is fixed in latest version of qvitter. vinilox probably has an older version

**Comment by moshpirit** [comment]
Reported, thank you!! :+1:
