### ISSUE TITLE
"Temporal line" as the default TL instead of "Public Temporal line"

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#38]
My "Temporal line" shows my **real** TL, not the "Public Temporal line", I don't know if it's a server configuration.

**Comment by hannesmannerheim** [comment]
i don't quite understand. you want it to redirect to https://status.vinilox.eu/moshpirit/all when just typing in https://status.vinilox.eu/ ? or when loggin in?

**Comment by moshpirit** [comment]
Mm, I think https://status.vinilox.eu/ should be the default TL and https://status.vinilox.eu/moshpirit/all the public one :\ that way, when we sing in, it appears our TL instead of the public one (and the same thing with the **gnu**social logo in the upper bar.

**Comment by hannesmannerheim** [comment]
i'm sorry, you've completely lost me now. when logging in you'r redirected to your personal timeline. that's how it should be. the urls is a gnusocial thing, and i think it makes sense to keep it as it is now.  https://status.vinilox.eu/ should show the same timeline both when logged in and logged out.
