### ISSUE TITLE
Hagstags with special characters are not highlighted

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#43]
I've tried to use #HabloEspañol (I speak Spanish) but I can't because the 'Ñ', the same happens if I use any tilde (Á,À,Â,...)

**Comment by jmontane** [comment]
For a reference, please read UAX #31
http://unicode.org/reports/tr31/

**Comment by mig42** [comment]
@moshpirit Are you sure? I tried with hashtag #Ñe or #ñe and it worked... It wasn't highlighted in the queet entry text area, but once published it worked just fine.

**Comment by moshpirit** [comment]
Oh, ok :) then, the issue should be: hagstags with special characters are not highlighted

**Comment by llebegue** [comment]
Looks like it's ok here : https://statusnet.lebegue.org/notice/458762

**Comment by knuthollund** [comment]
This bug can probably be closed? It is working now (also the example notice above is displaying properly - highlighted). Maybe it is running nightly gnusocial where UTF-8 stuff was added (emoji) - https://gitorious.org/social/mainline/commit/b639a2585655e3bded2357f175d43b3287561616
