### ISSUE TITLE
Unexpected refresh while editing profile

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#44]
If the 'edit profile' function is used on a timeline the page is automatically refreshed and we don't always have time to actually edit the profile and save it. 

The behaviour is ok if the  'edit profile'  function is used from a non-refreshable page such as followers list.

**Comment by hannesmannerheim** [comment]
same as https://github.com/hannesmannerheim/qvitter/issues/39

solved in latest gnu social nightly branch.
