### ISSUE TITLE
Unable to remove a profile background image

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#45]
There is a camera icon that allows to set a background image when editing a profile bit I couldn't find a way to remove it.

I had to connect to the database and remove it manually 

`delete from profile_prefs where profile_id=4 and namespace='qvitter' and topic='background_image';`

**Comment by hannesmannerheim** [comment]
if you select a background color, the image is (should be) removed

**Comment by vg** [comment]
+1

Removing a profile background picture should be an option. Hacks such as using a single colour picture are not a permanent solution. It would also be nice to have an option to set a separate colour to the profile background.
