### ISSUE TITLE
Remote profile options by default when we open another server user profile

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#46]
When we open the profile of another user, it shows a resume of this profile, and if click again, we get redirected to the server of this user, but with the "current classical version", we can use the "Remote profile options".

I.E.  
I'm using a server A and I want to see your profile (in server B), depending of the UI I have two options:

- Current classical UI: 
   - I open your profile directly and it open your server url (e.g. B.com)
   - I use Remote profile options and I can see your server B without exiting from mine (e.g. A.org)
- Qvitter: 
   - I open your profile and I get a resumed view
   - If I click on your "queets", it directly opens your server url (e.g. B.com)

**Comment by hannesmannerheim** [comment]
i'm confused. is it qvitter's or gnusocial's behaviour you want to change. there's no "remote profile options" in qvitter, just a popup.

**Comment by moshpirit** [comment]
No, it's qvitter behaviour, I want to see others profiles without exiting from mine.
If I see your profile, it appears the popup, and if I click in "queets", it send me to quitter. Well, I want to disable this sending and see your queets directly, just like "remote profile options" does in the classic UI.

**Comment by hannesmannerheim** [comment]
ah! i see now :) yes, this is something i've thought about also. marking it as an enhancement. thanks!

**Comment by moshpirit** [comment]
Thank you for your incredible work!! It would require much time to implement it?

**Comment by hannesmannerheim** [comment]
not terribly much time, but there's a lot to do :/

**Comment by postblue** [comment]
Suggestion for it: adding the "follow" button in remote profile.

**Comment by moshpirit** [comment]
I think you mean the popup, it has this button, if you can see it, please, tell us in #62 what browser, server and user are you using and who were you trying to follow.

**Comment by postblue** [comment]
So it has? Well, it isn't displayed. Tracking #62.
