### ISSUE TITLE
Special chars: wrong codification in quits from different nodes

### ISSUE THREAD

**Issue by efedoso** [hannesmannerheim/qvitter#52]
As of yesterday, special chars in texts written from users in different nodes (read from .no) appear with wrong codification. If you open a new tab for the user profile, then characters are right. I've read other people complaining about the same.
![tl](https://cloud.githubusercontent.com/assets/10584385/5792755/96a0fa52-9f28-11e4-854e-78119b7f5e8f.jpg)
![tl2](https://cloud.githubusercontent.com/assets/10584385/5792756/96a158f8-9f28-11e4-992d-795b110c1d5c.jpg)
![up](https://cloud.githubusercontent.com/assets/10584385/5792757/96a33498-9f28-11e4-95a0-621665e89111.jpg)
![up2](https://cloud.githubusercontent.com/assets/10584385/5792758/96a6e12e-9f28-11e4-9ded-e27cb85933b5.jpg)

**Comment by hannesmannerheim** [comment]
both users, ramonmage and nicolas has their account on quitter.es. is this the common denominator for all of these issues?

**Comment by efedoso** [comment]
Also on quitter.se, that I'm aware.

**Comment by hannesmannerheim** [comment]
example?

**Comment by efedoso** [comment]
![tl3](https://cloud.githubusercontent.com/assets/10584385/5792810/075283ae-9f2b-11e4-96ef-41737f53682d.jpg)
![up3](https://cloud.githubusercontent.com/assets/10584385/5792811/0753d362-9f2b-11e4-8ac9-ab065ba1b39d.jpg)

**Comment by hannesmannerheim** [comment]
which instance are you reading from?

**Comment by efedoso** [comment]
.no

**Comment by hannesmannerheim** [comment]
thx.

weird thing is this notice got corrupted:
https://quitter.no/notice/113165

but this didn't:
https://quitter.no/notice/113219

both are .es -> .no, by the same user and pretty close in time..

can this issue be found anywhere not involving quitter.no?

**Comment by efedoso** [comment]
I'm checking and quits from .zone are right.

**Comment by efedoso** [comment]
What do you mean, «not involving quitter.no»?

**Comment by hannesmannerheim** [comment]
an example of, e.g., a quitter.zone notice that ended up corrupted on e.g. quitter.se

**Comment by hannesmannerheim** [comment]
@mmn if you have time, can you understand why https://quitter.no/notice/113165 is corrupted but https://quitter.no/notice/113219 isn't?

**Comment by efedoso** [comment]
In the notices you've linked, the second one does not contain any special char. In the first one, the correct text should be «¿Aún estás aquí?»: https://quitter.es/notice/19880

**Comment by hannesmannerheim** [comment]
¿ is a special char no?

**Comment by efedoso** [comment]
Apparently, the problem comes with accents.

**Comment by efedoso** [comment]
Also, I think I've seen a quit in a northern language also with codification errors. Link some for me to check, if you like.

**Comment by hannesmannerheim** [comment]
in https://quitter.no/notice/112820 a ¿ is enough

**Comment by efedoso** [comment]
Yes, the «¿» is kept, but «Â» is wrongly added. That is not a Spanish char.

**Comment by hannesmannerheim** [comment]
exatly. "¿" gets corrupted into "Â¿".

i find it strange that it's not consistent.

unless we find the corruption somewhere not involving quitter.no, i think it is a quitter.no configuration error.

**Comment by efedoso** [comment]
I'm going to ask in the Global Timeline; hope somebody answers.

**Comment by efedoso** [comment]
Strange: right now I've found a quit from someone in quitter.es with an «í» and not corrupeted, 1 min. later a quit from same user corrupted.

**Comment by hannesmannerheim** [comment]
yes, this inconsistency seems like a key to understanding this.

**Comment by efedoso** [comment]
Now a quit from status.pirati.ca also corrupted: https://quitter.no/notice/113503

**Comment by hannesmannerheim** [comment]
i'm leaning more and more towards this being a quitter.no configuration problem. @knuthollund, any ideas?

**Comment by efedoso** [comment]
Other user in quitter.no has confirmed same issue; waiting for someone outside quitter.no to confirm or deny.

**Comment by efedoso** [comment]
I've just realised: registerd another account in quitter.es, let me check from there.

**Comment by efedoso** [comment]
Apparently, no problem reading quits in quitter.no from quitter.es.

**Comment by hannesmannerheim** [comment]
let's wait and see if @knuthollund has any idea. maybe he changed something with the database lately?

**Comment by efedoso** [comment]
All right. Just let me know if I can help.

**Comment by efedoso** [comment]
Someone tells me there's no problem reading from quitter.zone either.

**Comment by knuthollund** [comment]
Tested norwegian chars æøå  ØÆÅ between IS and NO - seems to be ok. Also sombody from .zone responded to that with the chars , which again displayed ok. 
https://quitter.no/notice/114590

**Comment by knuthollund** [comment]
But from .es - they are displayed wrong this queet on .es ->https://quitter.es/notice/22970 - landed as -> https://quitter.no/notice/114627 on .no 
So what is wrong then - .es sending wrong or .no interpreting wrong .. hmmm

**Comment by efedoso** [comment]
Happens also when sent from .se

**Comment by knuthollund** [comment]
But not from .is :)

**Comment by knuthollund** [comment]
Hmm if anybody knows. Yesterday I started to use php5-fpm togheter with FastCGI.
In php.ini for php5-fpm I see this setting.
; PHP's default character set is set to empty.
; http://php.net/default-charset
;default_charset = "UTF-8"

Should that be "enabled" - meaning setting default charset to UTF-8?

**Comment by hannesmannerheim** [comment]
i don't know. these are the worst kind of errors...

**Comment by knuthollund** [comment]
yupp - have asked MMN-o on irc. he is using php5-fpm too ...

**Comment by efedoso** [comment]
I would say yes. I always uncomment that statement.

**Comment by knuthollund** [comment]
On qutter.no a change in php5-fpm - php.ini file did it. It works ok now.
This setting (as shown above in previous comment) - default_charset = "UTF-8" needs to be enabled.

**Comment by hannesmannerheim** [comment]
awesome :))
