### ISSUE TITLE
... link sometimes doesn't work

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#61]
When we enter a lot of characters, it's showed in the note a "..." and if we push it, it shows the entire message. The point it's I'm trying to open the "..." of [this note](https://quitter.zone/notice/22802) from quitter.zone and I can't.

I think it should be better to show this "..." only passed the 500 chars, without being care about what server are we using.

**Comment by hannesmannerheim** [comment]
can't do that with qvitter. it's an ostatus thing. but notice the ostatus-symbol in the corner, it leads to the full post on .es
