### ISSUE TITLE
Sometimes the "Follow" button doesn't appears

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#62]
I have a help account on Quitter.zone and sometimes, users tell me that they haven't been able to see this button.

**Comment by hannesmannerheim** [comment]
it's a known issue i've heard from users on quitter.no. very mysterious! the may appear if they temporarily change the browser window witdh to a narrow window... 

maybe it's a specific browser causing it, maybe it's a browser plugin?

**Comment by moshpirit** [comment]
I don't know, it works fine for me

**Comment by hannesmannerheim** [comment]
keep your eyes open for any clues as to which browser/setting is causing this!

**Comment by moshpirit** [comment]
Sure! I'll let you know!

**Comment by postblue** [comment]
To make it clear, is it about the `follow-button` not displayed in `user-actions` of a `popup-external-profile`?

![](http://i.imgur.com/ny7WM4j.png)

**Comment by moshpirit** [comment]
Exactly, please, in what conditions you found this bug? Every information it's appreciated

**Comment by hannesmannerheim** [comment]
here's an old thread about this issue https://quitter.no/notice/73543

**Comment by hannesmannerheim** [comment]
@postblue can you try the latest commit and see if it fixes it? it's just a wild guess, since i can't reproduce it

**Comment by postblue** [comment]
@moshpirit Just clicking a @ mention in my timeline (heirds.eu/postblue/all), what displays the remote profile (and I like how it does).

@hannesmannerheim Let's do this. "cd /var/www/herds; git pull -u; php scripts/upgrade.php; cd /var/www/herds/plugins/Qvitter; git pull -u"

![](http://i.imgur.com/q6Cs9l9.png)

No chance. :/ Using Firefox 35.0.

**Comment by hannesmannerheim** [comment]
@postblue how about now?

**Comment by postblue** [comment]
Unfortunately, not yet.

**Comment by hannesmannerheim** [comment]
ok :/ thanks for testing

**Comment by hannesmannerheim** [comment]
i'm out of ideas now..

**Comment by postblue** [comment]
No problem, it's just one git pull, clear cache, CTRL F5.

**Comment by moshpirit** [comment]
- SO: Windows 7 (64 bits)
- Web browser: Waterfox 34.0.1
- Extensions/plugins: Adblock Edge (using Ultimate List by fanboyz) NoScript, Request Policy and Self-Desctructing Cookies
- User: [librepensador on quitter.es](https://quitter.es/notice/65356)

**Comment by postblue** [comment]
I totally forgot to test without AdBlock! Because it's named `follow-button`, it's hidden by one of my lists (Fanboy's Social Blocking List, I think). It's working on Herds if I deactivate the extension for the domain.

**Comment by hannesmannerheim** [comment]
great!! thanks! i'll rename it to something else

**Comment by hannesmannerheim** [comment]
fixed in https://github.com/hannesmannerheim/qvitter/commit/5ffe3faf96590fbfa957de91d7a23585c03594a8
