### ISSUE TITLE
Undefined index: code

### ISSUE THREAD

**Issue by postblue** [hannesmannerheim/qvitter#69]
This is flooding my error.log file:

```
FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: code in /var/www/herds/plugins/Qvitter/QvitterPlugin.php on line 228" while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: herds.eu, request: "GET /api/statuses/friends_timeline.json?since_id=14634&t=1421756567038 HTTP/1.1", upstream: "fastcgi://unix:/var/run/herds.sock:", host: "herds.eu", referrer: "https://herds.eu/postblue/all"
```

Qvitter is enabled by default in `config.php`.

**Comment by hannesmannerheim** [comment]
sorry about that, https://github.com/hannesmannerheim/qvitter/commit/4e6744098d0adbc207c4a2f9cece1561e2b0a2e0 should fix it

**Comment by postblue** [comment]
Indeed it does, thank you very much! I appreciate the work you are doing, and the evolution of qvitter. Each day it is better! Now I have to find in gnusocial code why the hell I have an undefined language in lib/language.php on my singleuser instance but not on my community one... ;)
