### ISSUE TITLE
Duplication notifications when scroll down and js...

### ISSUE THREAD

**Issue by gurumelo** [hannesmannerheim/qvitter#73]
Hello, if you are in notifications. And scroll down. Js in action. if you up and then down, another time js, and notifications duplicates. Thanks!

**Comment by hannesmannerheim** [comment]
which instance are you using? this should be fixed on .se already

**Comment by gurumelo** [comment]
gnusocial.net i am going to git pull. Thanks.

**Comment by hannesmannerheim** [comment]
was this issue solved by updating?

**Comment by gurumelo** [comment]
Yes, all correct. Thank you very much.
