### ISSUE TITLE
Lock the master branch for avois trolling

### ISSUE THREAD

**Issue by softastur** [hannesmannerheim/qvitter#76]
As i said in the title, moderate INMEDIATELY this repository in order to avoid troll people.

As example there is an language called "Español (ahorita)" which doesn't exist, it's despective for latin american people.

Please, consider this because is very important.

Thank you.

**Comment by hannesmannerheim** [comment]
lol i created that language because it was fun, i'm the only moderator here

**Comment by hannesmannerheim** [comment]
are you sure it is despective? i didn't get that feeling

**Comment by hannesmannerheim** [comment]
but if that's how it is perceived, sure, i'll remove it. are you latin american? maybe you can create a latin american spanish translation?

**Comment by hannesmannerheim** [comment]
i considered it more like a meme on quitter. there's https://quitter.es/group/ahoritateam and https://quitter.es/ahorita for example?

**Comment by softastur** [comment]
No, i am not latin american but as spanish speaker sounds me like a bad joke. Anyway, the main problem here is anyone can write in the master branch without forking it, and that represents a problem. If this message sounds rude for you, sorry it'is not my intention.

To check what i'm saying:

1º: Make an a new account or reuse another one
2º: Go to edit a file in this repo (it doesn't matter which)
3º: Edit with your non-privileged account and without forking it
4º: Finally apply the changes to master branch.

Thank you.

**Comment by hannesmannerheim** [comment]
when i try that i get the message "You're editing a file in a project you don't have write access to."
