### ISSUE TITLE
Space after user name when replying.

### ISSUE THREAD

**Issue by efedoso** [hannesmannerheim/qvitter#78]
When you reply to somebody, cursor stays right after its user name, so reference to this user is lost, as «@username» gets extended as «@usernameandreplytext». Should a white space be added automatically after last user name in a reply.

**Comment by hannesmannerheim** [comment]
there's supposed to be a space there, and it works for me. which browser are you using?

**Comment by efedoso** [comment]
Yes, there is indeed. Sorry. Must have been my bad :(

**Comment by hannesmannerheim** [comment]
i don't rule out there can be a bug that sometimes makes the space disappear, tell me if you see it again, and if there was any special circumstances
