### ISSUE TITLE
Site background image overidden at each git pull

### ISSUE THREAD

**Issue by llebegue** [hannesmannerheim/qvitter#83]
When git pulling qvitter plugin I need to manually change qvitter.js here : 

449:		$('body').css('background-image', 'url(' + window.fullUrlToThisQvitterApp + 'img/lebegue.org.bass.background.png)');

Could it be externalized ?

`$config['site']['qvitter']['sitebackground'] = 'img/lebegue.org.bass.background.png'; `

**Comment by hannesmannerheim** [comment]
duplicate of issue #41
