### ISSUE TITLE
Notifications indicator is not reset ["mark all as read"-button]

### ISSUE THREAD

**Issue by moshpirit** [hannesmannerheim/qvitter#86]
It's a very repetitive bug: we get some notifications, we see them but the indicator persist with the number of these notifications. 
It's not a server or browser thing, I think, just a qvitter bug.

A lot of users have reported it to me, but I thought it was a known bug, I came here but I didn't find any issue :(

**Comment by hannesmannerheim** [comment]
it's because i (hope i) recently fixed that bug. it will probably go away when the admins update

**Comment by moshpirit** [comment]
Oh, thanks, Hannes!! :D

**Comment by hannesmannerheim** [comment]
if the bug persists even after updating, please notify me here!

**Comment by moshpirit** [comment]
Yesterday I didn't use GNU social, so I got a lot of notifications, today I've seen all of them but I still have the (1) notification.

**Comment by hannesmannerheim** [comment]
even after scrolling down really far (several pages) in the notifications timeline?

**Comment by moshpirit** [comment]
yes :\ to almost an entire week ago

**Comment by hannesmannerheim** [comment]
:( thx for reporting. i think we need that "mark all as read"-button

**Comment by moshpirit** [comment]
Good solution! :+1:

**Comment by moshpirit** [comment]
OK, I've just got a new notification and looks like now I have not this (1) anymore :D

**Comment by hannesmannerheim** [comment]
fixed

**Comment by moshpirit** [comment]
I see, thank you so much for your work!
