### ISSUE TITLE
wrong term

### ISSUE THREAD

**Issue by mama21mama** [hannesmannerheim/qvitter#87]
exclusively for quitter.se perhaps quuet correct term.

but I think the term is also wrong in quitter.
the correct translation is Dent

Queet wrong

Dent is well

**Comment by hannesmannerheim** [comment]
i'm sticking with queets

queet is also well

**Comment by mama21mama** [comment]
then I will make a fork with the correct terminology. https://github.com/mama21mama/qvitter

**Comment by postblue** [comment]
@mama21mama A "dent" refers to a message on identi.ca, one of the many instances of the StatusNet software. A "status" might be the good term for it, but now we are using GNU social, and we can imagine new terms, new words. On the other hand, a "queet" refers to the Quitter website, and not all websites are Quitter, but it's the website *qvitter* was created for. **TL;DR**: There is no such thing as a correct terminology.

**Comment by mama21mama** [comment]
In that reality you live. Old StatusNet users who are most users GNUsocial we call Dent. Only the minority uses the term Quuet.

I only speak of echos and realities. With your thought you managed not impose anything.

**Comment by mama21mama** [comment]
To see the polls

http://legadolibre.com.ar/conversation/146906#notice-146912

**Comment by hannesmannerheim** [comment]
it's not something i'm changing. if i were to change it, i would change it to "notice", since that's what they are called in the default ui.

**Comment by mama21mama** [comment]
the plugin is not official, not in the source code GNUsocial. Therefore the term is not official. comrade
