### ISSUE TITLE
Uploading picture without writing in textbox, makes qvitter "spinn"

### ISSUE THREAD

**Issue by knuthollund** [hannesmannerheim/qvitter#90]
If you upload a picture without writing anything in the text box (queet box), it makes qvitter spinn and the user are not able to stop it and continue writing the notice. Just entering a space first in the box will help.
see screenshot.

**Comment by knuthollund** [comment]
![bug](https://cloud.githubusercontent.com/assets/3600521/5881224/5287a954-a33f-11e4-81bc-b2a3a36fd4dd.png)

**Comment by hannesmannerheim** [comment]
with latest qvitter version? i fixed this exact bug recently, and it works for me now.

**Comment by knuthollund** [comment]
Ehhh so what is the latest qvitter version? version nr?
Well it is a few days since I pulled a new version from git.

**Comment by knuthollund** [comment]
All ok when I pulled new code. close issue.
