### ISSUE TITLE
mentions not in notifications

### ISSUE THREAD

**Issue by hannesmannerheim** [hannesmannerheim/qvitter#92]
for some reason mentions doesn't show up in notifications if the post is shortened and the mention is in the chopped of part. _although_, they do show up in mentions-stream. 

both notifications and gnu socials native mentions use common_find_mentions(). i can't figure out why it doesn't work for notifications.

**Comment by hannesmannerheim** [comment]
to solve this we need to be able to run common_find_mentions() on the unshortened notice content. is that possible in the onStartNoticeDistribute-hook?

or we need to move notifications to an earlier hook, before the content is shortened. but in onStartNoticeSave we can't get the notice_id....... right?

**Comment by hannesmannerheim** [comment]
relevant code in qvitter is at ~line 637 in QvitterPlugin.php

**Comment by mmn** [comment]
Remind me if I haven't replied to this by tomorrow evening!

**Comment by mmn** [comment]
I haven't done it yet. Remind me if I haven't replied to this by tomorrow evening! Good night.

**Comment by mmn** [comment]
Darnit! You'd better start reminding me about this bug :D
