### ISSUE TITLE
Implementing "Network public timeline" in GNU social

### ISSUE THREAD

**Issue by mmn** [hannesmannerheim/qvitter#96]
I'm implementing a "Network public timeline" in GNU social nightly, which will be pushed as master pretty soon. It will give a '/main/public' and a '/main/all' feed to all instances, regardless of type. However, the '/main/all' will by default not be accessible without authentication on any site which is not of the siteprofile "public" (can be configured by administrator on /panel/access ).

That also means the "Public and External" API timeline which Qvitter has implemented can be deprecated/removed for later commits of GNU social.

The API endpoint is /api/statuses/networkpublic_timeline.json and extends the public timeline. It should reasonably not behave any differently than "public_and_external_timeline.json" - except that we're filtering out anything that is not a 'post' verb directly. (I believe that means no favorite/repeat will be delivered). That's however something that will probably change, as I think _all_ activites should be delivered via the API and it's up to the clients to handle them.

I was thinking about making a patch that will replace all the 'data-stream-name' attributes etc. with 'statuses/networkpublic_timeline.json' instead of the current 'statuses/public_and_external_timeline.json' and adds an if-statement around the route-registration for the relevant paths and wherever else it is necessary to be backward compatible. Is that desired?
(I'll be fiddling a bit more with it on the GNU social side, but what I wrote above should not be subject to change).

An easy way to change all the paths in all the .php and .js files is (current working directory being the Qvitter folder): <code>find . \\( -name '\*.php' -o -name '\*.js' \\) -print0 | xargs -0 sed -i 's/public[\_-]and[\_-]external/networkpublic/g'</code> (should be manually checked though, since it also changes the route registration lines).

**Comment by hannesmannerheim** [comment]
awesome! i can make qvitter ready for this tomorrow.

**Comment by mmn** [comment]
I'm probably going to be unavailable for the weekend (working late evening tonight, then something like 10.45-23.30 tomorrow). So you know. But all fixes should be pushed to nightly of GNU social anyway and the only thing I haven't investigated yet is that qvitter defaults to public_timeline for '/' on quitter.es for example, which I haven't checked yet is because of me or a configuration option in qvitter .)

**Comment by mmn** [comment]
Oooh, silly me. The reason that no remote posts are  listed is because the public_timeline.json no longer reports remote posts despite having $config['public']['localonly']=false.  So qvitter should choose the "default" (shown on path / ) timeline based on the value of localonly.

One thing with the GNU social stuff I've made is that there is a new action, "StartpageAction", which intends to allow users to implement something like a splash page or specially designed front page in later revisions. Right now it just forwards to /main/public or /main/all depending on the localonly value (but when running Qvitter it is overridden by the QvitterAction anyway ;)).

**Comment by mmn** [comment]
In the end of the weekend or beginning of next week I'll send the required patches which can also maintain certain backward compatibility with the current implementations out there.

**Comment by hannesmannerheim** [comment]
"i can make qvitter ready for this tomorrow"

LOL! ursäkta dröjsmålet @mmn
