### ISSUE TITLE
Notification number / realtime updates

### ISSUE THREAD

**Issue by hfroese** [hannesmannerheim/qvitter#97]
The number of new notifications doesn't appear at the left menu.

Real time updates in classic quitter (theme: neo-blue and meteor server) doesn't work either.

**Comment by hannesmannerheim** [comment]
i know nothing about meteor stuff.

for the new notifications count to display, you need to either upgrade to latest gnusocial or follow step 3 in the readme file. i should have notified you about that change, sry. i just posted it to the !qvitter group.
